#ifndef BFM_ENGINE_TYPES_H
#define BFM_ENGINE_TYPES_H
/* src/shared/engine_types.h — shared engine struct/union types + typedefs (Phase 15 §14c,
 * Phase 20 typedef lift). Generated by tools/build_engine_types.py from the matched bodies
 * in the source overlay. Defined ONCE here (0 same-name-different-layout collisions) so the
 * struct/typedef-using shared functions propagate fleet-wide via engine_core.h. Included by
 * common.h consumers. */
#include "common.h"

struct vec;
struct V8;
struct M8012AF0C;
struct Vec;
struct S80131E00;
struct obj;
struct S8013A250;
struct Inner8013A4C4;
struct S8013A4C4;
struct VecA;
struct VecB;
struct S80143BDC;
struct S;
struct S_8014AD30;
struct S8014C010;
struct S8;
struct UnalignedPair;
struct Packed8;
struct SubE6F8;
struct SubED80;
struct SubF24C;
struct S8014FDF4;
struct V3;
struct S80151ECC;
struct S80153150;
struct Obj;
struct M8;
struct S8016380C;
struct B16;
struct U8;
struct S8_80172780;
struct S8_80172894;
struct S801730FC;
struct S80126B38;
struct BigCopy;
struct S8013A0A4;
struct S8013A164;
struct S_80149744;
struct S_8014A3E0;
struct B8014;
struct copy00;
struct Vec4s;
struct Src80172E20;
struct V4s80147514;
struct Quad;
struct A;
struct B;
struct Bv;

struct vec {
    s32 unk0;
    s32 unk4;
    s32 unk8;
    s32 unkC;
    s32 unk10;
    s32 unk14;
    s32 unk18;
};

struct V8 { char b[8]; };

struct M8012AF0C { short a, b, c, d; };

struct Vec {
    s16 unk0;
    s16 unk2;  /* x */
    s16 unk4;
    s16 unk6;  /* y */
    s16 unk8;
    s16 unkA;  /* z */
};

struct S80131E00 {
    char pad[0xB0];
    s32 field_B0;
};

struct obj {
    u8 pad0[0x4];
    s16 unk4;
    u8 pad6[0x2];
    s32 unk8;
};

struct S8013A250 {
    u8 pad8[8];
    s32 unk8;      /* 0x8 */
    u8 unkC;       /* 0xC */
};

struct Inner8013A4C4 {
    u8 pad28[0x28];
    s16 unk28;     /* 0x28 */
    s16 unk2A;     /* 0x2A */
};

struct S8013A4C4 {
    s16 unk0;      /* 0x0 */
    s16 unk2;      /* 0x2 */
    struct Inner8013A4C4 *unk4;  /* 0x4 */
    u8 padE[6];
    s16 unkE;      /* 0xE */
};

struct VecA {
    s16 unk0;
    s16 unk2;  /* x */
    s16 unk4;
    s16 unk6;  /* y */
    s16 unk8;
    s16 unkA;  /* z */
};

struct VecB {
    s16 unk0;  /* x */
    s16 unk2;  /* y */
    s16 unk4;  /* z */
};

struct S80143BDC {
    s16 f0, f2, f4, f6, f8, fA, fC, fE;
    s32 f10;
};

struct S {
    u8  pad0[0x7E]; /* 0x0..0x7D */
    u16 f7E;        /* 0x7E */
};

struct S_8014AD30 {
    s16 h0;
    s16 h1;
    s16 h2;
    s16 h3;
    s32 w0;
    s32 w1;
    s32 w2;
};

struct S8014C010 {
    s16 h0;
    s16 h1;
    s16 h2;
    s16 h3;
    s32 w8;
    s32 wC;
    s32 w10;
};

struct S8 { u32 a; u32 b; } __attribute__((packed, aligned(1)));

struct UnalignedPair {
    int a;
    int b;
} __attribute__((packed, aligned(1)));

struct Packed8 {
    int a;
    int b;
} __attribute__((packed));

struct SubE6F8 {
    u8 pad0[6];
    u16 f6;
    u8 pad8[2];
    u16 fA;
    u8 padC[2];
    u16 fE;
    u8 pad10[0x78];
    u16 f88;
    u16 f8A;
    u16 f8C;
    u8 pad8E[0xF2];
    s32 f180;
};

struct SubED80 {
    u8 pad0[6];
    u16 f6;
    u8 pad8[2];
    u16 fA;
    u8 padC[2];
    u16 fE;
    u8 pad10[0x34];
    s32 f44;
    u8 pad48[0x40];
    u16 f88;
    u16 f8A;
    u16 f8C;
    u8 pad8E[0x16A];
    s32 f1F8;
};

struct SubF24C {
    u8 pad0[6];
    u16 f6;
    u8 pad8[2];
    u16 fA;
    u8 padC[2];
    u16 fE;
    u8 pad10[0x34];
    s32 f44;
    u8 pad48[0x40];
    u16 f88;
    u16 f8A;
    u16 f8C;
    u8 pad8E[0x16A];
    s32 f1F8;
};

struct S8014FDF4 {
    s16 pad0[3];   /* 0x0,0x2,0x4 */
    s16 f6;        /* 0x6 */
    s16 pad8;      /* 0x8 */
    s16 fA;        /* 0xA */
    s16 padC;      /* 0xC */
    s16 fE;        /* 0xE */
    s16 pad[0x3C]; /* up to 0x88 */
    s16 f88;       /* 0x88 */
    s16 f8A;       /* 0x8A */
    s16 f8C;       /* 0x8C */
};

struct V3 { s16 x; s16 y; s16 z; };

struct S80151ECC {
    u8 pad0[0x64];
    s16 f64;        /* 0x64 */
    u8 padr[0x78];
    u8 fDE;         /* 0xDE */
};

struct S80153150 {
    u8 pad0[0x60];
    s16 f60;   /* 0x60 */
    s16 f62;   /* 0x62 */
    u16 f64;   /* 0x64 */
    u8 padr[0x78];
    u8 fDE;    /* 0xDE */
};

struct Obj {
    short unk0;
    unsigned short idx;
};

struct M8 { u8 b[8]; };

struct S8016380C {
    u8 _pad[0x44];
    struct M8 m;
};

struct B16 { s32 w[4]; };

struct U8 {
    char b[8];
} __attribute__((aligned(1)));

struct S8_80172780 { s16 m[4]; };

struct S8_80172894 { s16 m[4]; };

struct S801730FC {
    u8 pad[0xB8];
    u16 unkB8;     /* 0xB8 */
};

struct S80126B38 { s32 a; s32 b; } __attribute__((packed));

struct BigCopy { s32 words[41]; };

struct S8013A0A4 {
    u8 pad0[4];
    s16 field_4;
    u8 pad6[2];
    s32 field_8;
    u8 pad12[10];
    u16 field_16;
    u8 pad18[6];
    u8 field_1E;
    u8 pad1F[15];
    s16 field_2E;
};

struct S8013A164 {
    char pad0[0x4];
    s16 field_04;      /* 0x04 */
    char pad06[0x2];
    s32 field_08;      /* 0x08 */
    char pad0C[0xC];
    u16 field_18;      /* 0x18 */
    char pad1A[0x26];
    s16 *field_40;     /* 0x40 */
};

struct S_80149744 {
    char pad44[0x44];
    s32 w44;       /* 0x44 */
    char pad48[0xAC - 0x48];
    u16 h_AC;      /* 0xAC */
};

struct S_8014A3E0 {
    char pad0[0x12];
    s16 h12;      /* 0x12 */
    char pad14[0x6];
    s16 h1A;      /* 0x1A */
    char pad1C[0x6C];
    u16 h88;      /* 0x88 */
    u16 h8A;      /* 0x8A */
    u16 h8C;      /* 0x8C */
};

struct B8014 { char b[8]; };

struct copy00 { s32 w[41]; };

struct Vec4s { s16 a, b, c, d; };

struct Src80172E20 {
    u8 pad0[6];
    u16 _6;
    u8 pad8[0xA - 8];
    u16 _A;
    u8 padC[0xE - 0xC];
    u16 _E;
};

struct V4s80147514 { s16 a, b, c, d; };

struct Quad { s32 a, b, c, d; };

struct A {
    u16 unk00; u16 unk02; u16 unk04;   /* 0x10 0x12 0x14 */
    u16 unk06;                         /* 0x16 (gap) */
    u16 unk08; u16 unk0A; u16 unk0C;   /* 0x18 0x1A 0x1C */
    u16 unk0E;                         /* 0x1E (gap) */
    u8  unk10; u8 unk11; u8 unk12;     /* 0x20 0x21 0x22 */
    u8  unk13;                         /* 0x23 (gap) */
    u8  unk14; u8 unk15; u8 unk16;     /* 0x24 0x25 0x26 */
    u8  unk17;                         /* 0x27 (gap) */
    s32 unk18;                         /* 0x28 */
};

struct B  { s32 w[8]; s32 tail[2]; };

struct Bv { s32 w[8]; };

typedef struct {
    u16 guard;  /* +0 */
    u16 pad;    /* +2 */
    u16 field;  /* +4 */
    u8  rest[14]; /* +6 .. +0x14 */
} Ent;

typedef struct { char pad[0x12]; s16 field_0x12; } Obj;

typedef struct {
    u16 f_0;
    u8 pad_2[0xA8];
    s16 f_AA;
    u8 pad_AC[0x60];
} Entry8014A238;

typedef struct {
    u16 unk0;
    u8 pad[0x6E];
    s16 unk70;
    u8 pad2[0x9A];
} Entry8014C118;

typedef struct {
    u16 unk0;
    u16 unk2;
    u16 unk4;
    u8 unk6;
    u8 unk7;
} Buf80153978;

typedef struct { s32 a, b, c; } S801563EC;

typedef struct {
    u8 pad[0x12];
    u16 field12;
} S801593E4;

typedef struct {
    u8 pad[0x20];
    S801593E4 *p20;
} A801593E4;

typedef struct { s32 w[8]; } Blk20;

typedef int (*DispatchFn)();

typedef struct {
    u8 pad6[0x6];
    u16 h6;
    u16 h8;
    u16 hA;
} SrcB964;

typedef struct {
    u8 pad8[0x8];
    u16 h8;
    u16 hA;
    u16 hC;
} DstB964;

typedef struct {
    s16 x;
    s16 y;
    s16 w;
    s16 h;
} Rect;

typedef struct { u8 b[8]; } Blk8;

/* Phase 22: lifted from ov_SC01_077.c (was a per-function prelude block) so the
 * struct-walled close=0 giants (func_80156B74, func_80156848, ...) propagate ×134.
 * NOTE: the typedef name `S8` (ordinary-identifier namespace, the s16 4-field engine
 * coord triple/quad used by D_80126AF0[]) coexists with the unrelated `struct S8`
 * TAG above (u32 2-field, namespace-distinct, used via `struct S8` in engine_core.h).
 * `B8` is layout-identical to Blk8 but kept under its draft name to avoid churning
 * the already-matched func_80156848. */
typedef struct { s16 a; s16 b; s16 c; s16 d; } S8;
typedef struct { u8 b[8]; } B8;

#endif /* BFM_ENGINE_TYPES_H */
