#ifndef BFM_ENGINE_TYPES_H
#define BFM_ENGINE_TYPES_H
/* src/shared/engine_types.h — shared engine struct/union types + typedefs (Phase 15 §14c,
 * Phase 20 typedef lift). Generated by tools/build_engine_types.py from the matched bodies
 * in the source overlay. Defined ONCE here (0 same-name-different-layout collisions) so the
 * struct/typedef-using shared functions propagate fleet-wide via engine_core.h. Included by
 * common.h consumers. */
#include "common.h"

struct vec;
struct V8;
struct M8012AF0C;
struct Vec;
struct S80131E00;
struct obj;
struct S8013A250;
struct Inner8013A4C4;
struct S8013A4C4;
struct VecA;
struct VecB;
struct S80143BDC;
struct S;
struct S_8014AD30;
struct S8014C010;
struct S8;
struct UnalignedPair;
struct Packed8;
struct SubE6F8;
struct SubED80;
struct SubF24C;
struct S8014FDF4;
struct V3;
struct S80151ECC;
struct S80153150;
struct Obj;
struct M8;
struct S8016380C;
struct B16;
struct U8;
struct S8_80172780;
struct S8_80172894;
struct S801730FC;
struct S80126B38;
struct BigCopy;
struct S8013A0A4;
struct S8013A164;
struct S_80149744;
struct S_8014A3E0;
struct B8014;
struct copy00;
struct Vec4s;
struct Src80172E20;
struct V4s80147514;
struct Quad;
struct A;
struct B;
struct Bv;
struct packed_word;
union word_bytes;
struct up;
struct Actor;
struct buf_8017F5BC;
struct sprite8;

struct vec {
    s32 unk0;
    s32 unk4;
    s32 unk8;
    s32 unkC;
    s32 unk10;
    s32 unk14;
    s32 unk18;
};

struct V8 { char b[8]; };

struct M8012AF0C { short a, b, c, d; };

struct Vec {
    s16 unk0;
    s16 unk2;  /* x */
    s16 unk4;
    s16 unk6;  /* y */
    s16 unk8;
    s16 unkA;  /* z */
};

struct S80131E00 {
    char pad[0xB0];
    s32 field_B0;
};

struct obj {
    u8 pad0[0x4];
    s16 unk4;
    u8 pad6[0x2];
    s32 unk8;
};

struct S8013A250 {
    u8 pad8[8];
    s32 unk8;      /* 0x8 */
    u8 unkC;       /* 0xC */
};

struct Inner8013A4C4 {
    u8 pad28[0x28];
    s16 unk28;     /* 0x28 */
    s16 unk2A;     /* 0x2A */
};

struct S8013A4C4 {
    s16 unk0;      /* 0x0 */
    s16 unk2;      /* 0x2 */
    struct Inner8013A4C4 *unk4;  /* 0x4 */
    u8 padE[6];
    s16 unkE;      /* 0xE */
};

struct VecA {
    s16 unk0;
    s16 unk2;  /* x */
    s16 unk4;
    s16 unk6;  /* y */
    s16 unk8;
    s16 unkA;  /* z */
};

struct VecB {
    s16 unk0;  /* x */
    s16 unk2;  /* y */
    s16 unk4;  /* z */
};

struct S80143BDC {
    s16 f0, f2, f4, f6, f8, fA, fC, fE;
    s32 f10;
};

struct S {
    u8  pad0[0x7E]; /* 0x0..0x7D */
    u16 f7E;        /* 0x7E */
};

struct S_8014AD30 {
    s16 h0;
    s16 h1;
    s16 h2;
    s16 h3;
    s32 w0;
    s32 w1;
    s32 w2;
};

struct S8014C010 {
    s16 h0;
    s16 h1;
    s16 h2;
    s16 h3;
    s32 w8;
    s32 wC;
    s32 w10;
};

struct S8 { u32 a; u32 b; } __attribute__((packed, aligned(1)));

struct UnalignedPair {
    int a;
    int b;
} __attribute__((packed, aligned(1)));

struct Packed8 {
    int a;
    int b;
} __attribute__((packed));

struct SubE6F8 {
    u8 pad0[6];
    u16 f6;
    u8 pad8[2];
    u16 fA;
    u8 padC[2];
    u16 fE;
    u8 pad10[0x78];
    u16 f88;
    u16 f8A;
    u16 f8C;
    u8 pad8E[0xF2];
    s32 f180;
};

struct SubED80 {
    u8 pad0[6];
    u16 f6;
    u8 pad8[2];
    u16 fA;
    u8 padC[2];
    u16 fE;
    u8 pad10[0x34];
    s32 f44;
    u8 pad48[0x40];
    u16 f88;
    u16 f8A;
    u16 f8C;
    u8 pad8E[0x16A];
    s32 f1F8;
};

struct SubF24C {
    u8 pad0[6];
    u16 f6;
    u8 pad8[2];
    u16 fA;
    u8 padC[2];
    u16 fE;
    u8 pad10[0x34];
    s32 f44;
    u8 pad48[0x40];
    u16 f88;
    u16 f8A;
    u16 f8C;
    u8 pad8E[0x16A];
    s32 f1F8;
};

struct S8014FDF4 {
    s16 pad0[3];   /* 0x0,0x2,0x4 */
    s16 f6;        /* 0x6 */
    s16 pad8;      /* 0x8 */
    s16 fA;        /* 0xA */
    s16 padC;      /* 0xC */
    s16 fE;        /* 0xE */
    s16 pad[0x3C]; /* up to 0x88 */
    s16 f88;       /* 0x88 */
    s16 f8A;       /* 0x8A */
    s16 f8C;       /* 0x8C */
};

struct V3 { s16 x; s16 y; s16 z; };

struct S80151ECC {
    u8 pad0[0x64];
    s16 f64;        /* 0x64 */
    u8 padr[0x78];
    u8 fDE;         /* 0xDE */
};

struct S80153150 {
    u8 pad0[0x60];
    s16 f60;   /* 0x60 */
    s16 f62;   /* 0x62 */
    u16 f64;   /* 0x64 */
    u8 padr[0x78];
    u8 fDE;    /* 0xDE */
};

struct Obj {
    short unk0;
    unsigned short idx;
};

struct M8 { u8 b[8]; };

struct S8016380C {
    u8 _pad[0x44];
    struct M8 m;
};

struct B16 { s32 w[4]; };

struct U8 {
    char b[8];
} __attribute__((aligned(1)));

struct S8_80172780 { s16 m[4]; };

struct S8_80172894 { s16 m[4]; };

struct S801730FC {
    u8 pad[0xB8];
    u16 unkB8;     /* 0xB8 */
};

struct S80126B38 { s32 a; s32 b; } __attribute__((packed));

struct BigCopy { s32 words[41]; };

struct S8013A0A4 {
    u8 pad0[4];
    s16 field_4;
    u8 pad6[2];
    s32 field_8;
    u8 pad12[10];
    u16 field_16;
    u8 pad18[6];
    u8 field_1E;
    u8 pad1F[15];
    s16 field_2E;
};

struct S8013A164 {
    char pad0[0x4];
    s16 field_04;      /* 0x04 */
    char pad06[0x2];
    s32 field_08;      /* 0x08 */
    char pad0C[0xC];
    u16 field_18;      /* 0x18 */
    char pad1A[0x26];
    s16 *field_40;     /* 0x40 */
};

struct S_80149744 {
    char pad44[0x44];
    s32 w44;       /* 0x44 */
    char pad48[0xAC - 0x48];
    u16 h_AC;      /* 0xAC */
};

struct S_8014A3E0 {
    char pad0[0x12];
    s16 h12;      /* 0x12 */
    char pad14[0x6];
    s16 h1A;      /* 0x1A */
    char pad1C[0x6C];
    u16 h88;      /* 0x88 */
    u16 h8A;      /* 0x8A */
    u16 h8C;      /* 0x8C */
};

struct B8014 { char b[8]; };

struct copy00 { s32 w[41]; };

struct Vec4s { s16 a, b, c, d; };

struct Src80172E20 {
    u8 pad0[6];
    u16 _6;
    u8 pad8[0xA - 8];
    u16 _A;
    u8 padC[0xE - 0xC];
    u16 _E;
};

struct V4s80147514 { s16 a, b, c, d; };

struct Quad { s32 a, b, c, d; };

struct A {
    u16 unk00; u16 unk02; u16 unk04;   /* 0x10 0x12 0x14 */
    u16 unk06;                         /* 0x16 (gap) */
    u16 unk08; u16 unk0A; u16 unk0C;   /* 0x18 0x1A 0x1C */
    u16 unk0E;                         /* 0x1E (gap) */
    u8  unk10; u8 unk11; u8 unk12;     /* 0x20 0x21 0x22 */
    u8  unk13;                         /* 0x23 (gap) */
    u8  unk14; u8 unk15; u8 unk16;     /* 0x24 0x25 0x26 */
    u8  unk17;                         /* 0x27 (gap) */
    s32 unk18;                         /* 0x28 */
};

struct B  { s32 w[8]; s32 tail[2]; };

struct Bv { s32 w[8]; };

struct packed_word { int w; } __attribute__((packed, aligned(1)));

union word_bytes {
    struct packed_word pw;
    u8 b[4];
};

struct up { int a; int b; } __attribute__((packed));

struct Actor {
    char pad0[0x12];
    u16 timer;       /* 0x12 */
};

struct buf_8017F5BC {
    short f0;   /* +0x00 */
    short f2;   /* +0x02 */
    short f4;   /* +0x04 */
    short f6;   /* +0x06 */
    short f8;   /* +0x08 */
    short fa;   /* +0x0a */
    short fc;   /* +0x0c */
    short fe;   /* +0x0e */
    int   f10;  /* +0x10 */
};

struct sprite8 {
    short f0;   /* +0x00 */
    short f2;   /* +0x02 */
    short f4;   /* +0x04 */
    short f6;   /* +0x06 */
    short f8;   /* +0x08 */
    short fa;   /* +0x0a */
    short fc;   /* +0x0c */
    short fe;   /* +0x0e */
    int   f10;  /* +0x10 (unwritten, reserved -> 20-byte struct => frame 0x40) */
};

typedef struct {
    u16 guard;  /* +0 */
    u16 pad;    /* +2 */
    u16 field;  /* +4 */
    u8  rest[14]; /* +6 .. +0x14 */
} Ent;

typedef struct { char pad[0x12]; s16 field_0x12; } Obj;

typedef struct {
    u16 f_0;
    u8 pad_2[0xA8];
    s16 f_AA;
    u8 pad_AC[0x60];
} Entry8014A238;

typedef struct {
    u16 unk0;
    u8 pad[0x6E];
    s16 unk70;
    u8 pad2[0x9A];
} Entry8014C118;

typedef struct {
    u16 unk0;
    u16 unk2;
    u16 unk4;
    u8 unk6;
    u8 unk7;
} Buf80153978;

typedef struct { s32 a, b, c; } S801563EC;

typedef struct {
    u8 pad[0x12];
    u16 field12;
} S801593E4;

typedef struct {
    u8 pad[0x20];
    S801593E4 *p20;
} A801593E4;

typedef struct { s32 w[8]; } Blk20;

typedef int (*DispatchFn)();

typedef struct {
    u8 pad6[0x6];
    u16 h6;
    u16 h8;
    u16 hA;
} SrcB964;

typedef struct {
    u8 pad8[0x8];
    u16 h8;
    u16 hA;
    u16 hC;
} DstB964;

typedef struct {
    s16 x;
    s16 y;
    s16 w;
    s16 h;
} Rect;

typedef struct { u8 b[8]; } Blk8;

typedef struct { s16 a; s16 b; s16 c; s16 d; } S8;

typedef struct { u8 b[8]; } B8;

typedef struct { u32 a, b, c, d; } Blk16;

typedef struct { Blk16 lo, hi; } Buf32;

typedef struct { s16 x, y, z, w; } PosT;

typedef struct { u16 x, y, z, w; } MoveT;

typedef struct { s32 vpx, vpy, vpz, vrx, vry, vrz, rz, super; } RView;

typedef struct { s16 vx, vy, vz, pad; } Svec_801372B0;

typedef struct { u32 attr; s16 x0, y0, x1, y1; u8 r, g, b, code; } Gline_801372B0;

typedef struct { u32 addr : 24; u32 len : 8; u8 r0, g0, b0, code; } P_TAG;

typedef struct {
    u8  pad[8]; /* 0x00 */
    u16 f8;     /* 0x08 */
    u16 fa;     /* 0x0a */
} MatEntry;

typedef struct { s32 a; s32 b[4]; } OtBlk;

typedef s32 (*ActorFn)(void *);

typedef struct {
    /* 0x00 */ s16 f0;
    /* 0x02 */ s16 f2;
    /* 0x04 */ s16 f4;
    /* 0x06 */ s16 pad6;
} Vec3;

typedef struct {
    /* 0x00 */ s16 a30;
    /* 0x02 */ s16 a2e;
    /* 0x04 */ s16 a2c;
    /* 0x06 */ s16 pad06;
    /* 0x08 */ s32 buf[2];
    /* 0x10 */ s16 a20;
    /* 0x12 */ s16 a1e;
    /* 0x14 */ s16 a1c;
} Loc;

typedef struct { s32 a, b, c, d; } S16;

typedef struct {
    u16 pad0;
    u16 idx;  /* offset 2 */
} S80153CCC;

typedef struct {
    u8 b[8];
} ImgRect8;

typedef struct { s16 id; s16 val; } Entry;

typedef void (*FuncPtr)(void);

typedef struct { int f0; int f1; int f2; int f3; } DStruct;

typedef struct { s32 w[8]; } Blk32;

typedef struct {
    short v0;   /* 0x00 */
    short v1;   /* 0x02 */
    short v2;   /* 0x04 */
    short pad6; /* 0x06 */
    short w0;   /* 0x08 */
    short w1;   /* 0x0A */
    short w2;   /* 0x0C */
    short padE; /* 0x0E */
    unsigned char b10; /* 0x10 */
    unsigned char b11; /* 0x11 */
    unsigned char b12; /* 0x12 */
    unsigned char b13; /* 0x13 */
    unsigned char b14; /* 0x14 */
    unsigned char b15; /* 0x15 */
    unsigned char b16; /* 0x16 */
    unsigned char b17; /* 0x17 */
    int   w18; /* 0x18 */
} Prim;

typedef struct {
    char _pad0;       /* 0x0 */
    unsigned char f1; /* 0x1 */
    unsigned char f2; /* 0x2 */
    char _pad3;       /* 0x3 */
    short f4;         /* 0x4 */
} Wave;

typedef void (*VoidFn)(void);

typedef unsigned int uint;

typedef struct { s16 a, b, c, d; } SV4;

typedef struct {
    s16 m[3][3];
    s16 pad;
    s32 t[3];
} MTX;

typedef struct { u16 vx, vy, vz, pad; } SVEC;

typedef void (*code_fn)(void);

typedef struct { u16 a, b, c, d; } SV4U;

typedef struct { short a, b, c; } SV3;


/* lifted for dedup propagation (Phase 29 T4 type-lift): func_8014E284 / func_80137DD4 */
typedef struct EntSC01077 {
    u16 f00;
    u8  pad02[4];
    u16 f06;
    u8  pad08[2];
    u16 f0A;
    u8  pad0C[2];
    u16 f0E;
    u8  pad10[0x10];
    s32 f20;
    u8  pad24[0x34];
    s32 f58;
    u16 f5C;
    u8  pad5E[0xAE];
} EntSC01077;

typedef struct { u32 addr : 24; u32 len : 8; u8 r0, g0, b0, code; } P_TAG_80137DD4;


/* --- lift_types.py fleet lift --- */
struct Cam8012E138 { u16 a, b, c; };
typedef struct { s32 w0, w4, w8, wC; s16 h10, hpad; s32 t0, t1, t2; } Mat32;

/* --- lift_types.py fleet lift --- */
struct Ent_801506A4 {
    unsigned short unk0;    /* 0x0 */
    char pad[0x5A];
    unsigned short unk5C;   /* 0x5C */
    char pad2[0x12];
    short unk70;            /* 0x70 */
};
struct Entry {
    u8 f0;
    u8 f1;
    u8 pad[0x1e];
};
struct Entry_8016E95C {
    u8 f0;
    u8 f1;
    u8 pad[0x1e];
};
struct In { s32 w0; s16 lo; s16 hi; s32 w2; };
struct PW8017E6D8 { int w; } __attribute__((packed, aligned(1)));
struct Q16 { s32 a, b, c, d; };
struct S126B58_inner { u16 pad[9]; u16 unk12; };
struct S126B58 { u8 pad[0x20]; struct S126B58_inner *unk20; };
struct S734 { s32 unk0; s32 unk4; s32 unk8; s32 unkC; u8 unk10[8]; s32 unk18;
              void (*unk1C)(s32, void *, s32); };
struct S8012C658 {
    u16 unk0;
    u16 unk2;
    u16 unk4;
    s16 unk6;
    s16 unk8;
    s16 unkA;
    s16 unkC;
    s16 unkE;
    s32 unk10;
};
struct S8012D664_8012D664 { short a, b, c; };
struct S80172C50 { s32 a; s32 b; } __attribute__((packed));
struct Sub2_80167540 {
    u8 pad0[0x44];
    s32 unk44;        /* 0x44 */
};
struct Sub_8015CD20 {
    u8 pad0[0x12];
    u16 unk12;      /* +0x12 */
};
struct Ent_8015CD20 {
    u16 unk0;       /* +0x00 */
    u8 pad2[0x1E];
    struct Sub_8015CD20 *unk20;  /* +0x20 */
    u8 pad24[0x94];
    s16 unkB8;      /* +0xB8 */
    u8 pad1BA[0x102];
    s8 unk1BC;      /* +0x1BC */
    u8 pad1BD[0x77];
    s32 unk234;     /* +0x234 */
};
struct W4 { u32 w; } __attribute__((packed, aligned(1)));
typedef struct actor4c {
    u8 pad00[0x20];
    struct actor4c *unk20;  /* 0x20 */
    u8 pad24[0x44 - 0x24];
    u32 unk44;              /* 0x44 */
    u8 pad48[0xB4 - 0x48];
    s32 *unkB4;             /* 0xB4  command-stream pointer */
    s16 unkB8;              /* 0xB8  countdown timer */
    s16 unkBA;              /* 0xBA */
    u8 unkBC;               /* 0xBC  program counter */
    u8 unkBD;               /* 0xBD */
    u8 padBE[0xDC - 0xBE];
    u8 unkDC;               /* 0xDC */
    u8 padDD[0x1A8 - 0xDD];
    u8 unk1A8;              /* 0x1A8 */
} Actor4C;
typedef struct { u8 d[4]; } __attribute__((packed, aligned(1))) B4;
typedef struct { u8 d[4]; } __attribute__((packed, aligned(1))) B4_80165140;
typedef struct { u8 d[8]; } __attribute__((packed, aligned(1))) B8_80165140;
typedef struct Bar {
    unsigned char b0;     /* 0x0 */
    unsigned char b1;     /* 0x1 */
    unsigned char b2;     /* 0x2 */
    unsigned char tag;    /* 0x3 */
    unsigned int a;       /* 0x4 */
    unsigned int b;       /* 0x8 */
} Bar;
typedef struct {
    u8 r, g, b, pad0;
    u8 dr, dg, db, pad1;
    s16 vx, vy, vz, tm;
} Blip_8018F694;
typedef struct { u32 w[38]; } Blk152;
typedef struct { s32 w[8]; } Blk20_8016DF5C;
typedef struct { s32 w[8]; } Blk32_998;
typedef struct { u8 d[0x60]; } Blk60;
typedef struct { u8 b[8]; } Blk8_8017B238;
typedef struct { u8 b[8]; } Blk8_8017B238_8017B238;
typedef struct { u8 b[8]; } Blk8_8017B614;
typedef struct {
    u8 f0, f1, f2, f3;
    struct { s16 a, b, c, d, e, g; } ent[16];
} Blk_8016CF04;
typedef struct {
    u8 f0, f1, f2, f3;
    struct { s16 a, b, c, d, e, g; } ent[16];
} Blk_8016CF04_8016CF04;
typedef struct { u16 f0; u16 f2; u16 f4; u16 f6; } Blk_80178D40;
typedef struct {
    u8 b[8];
} Blob8;
typedef struct { u16 f0, f2, f4; s16 f6; } Box;
typedef struct { u16 f0, f2, f4; s16 f6; } Box_80133784;
typedef struct {
    s32 op;
    union {
        s32 w;
        void *p;
        s16 h[2];
        u16 uh[2];
    } a;
} Cmd_80178D40;
typedef struct { s16 vx, vy; } DVECTOR2;
typedef struct { u32 w[23]; } DrawEnv;
typedef struct { u32 w[23]; } DrawEnv_8013DD68;
typedef struct { DrawEnv_8013DD68 env; u8 pad[0x0C]; } Buf_8013DD68;
typedef struct { s32 f0; } E4;
typedef struct { s32 f0; u8 pad[0x18]; } E_3B7AC;
typedef struct {
    /* 0x0 */ s16 f0;
    /* 0x2 */ s16 f2;
    /* 0x4 */ s16 f4;
    /* 0x6 */ s16 f6;
} Elem;
typedef struct { u8 _pad[0x34]; } Elem52_801B5094;
typedef struct { s16 e[4]; } ElemK;
typedef struct { int a; short cmd; short b; } Elem_8012ACE0;
typedef struct { int a; short cmd; short b; } Elem_8012ACE0_8012ACE0;
typedef struct {
    /* 0x0 */ s16 f0;
    /* 0x2 */ s16 f2;
    /* 0x4 */ s16 f4;
    /* 0x6 */ s16 f6;
} Elem_801347A0;
typedef struct {
    u16 f0;
    u8 pad0[0x4e];
    int f50;
    u8 pad1[0x14];
} Ent_80164930;
typedef struct {
    u16 f0;
    u8 pad0[0x4e];
    int f50;
    u8 pad1[0x14];
} Ent_80164930_80164930;
typedef struct Entry_8012DDA4 {
    u16 active;
    unsigned char pad[0x10C - 2];
} Entry_8012DDA4;
typedef struct Foo {
    unsigned char pad[0xc];
    unsigned int count;   /* 0xc */
    int field10;          /* 0x10 */
} Foo;
typedef struct {
    u16 f0;   /* 0x0 */
    u16 f2;   /* 0x2 */
    u16 f4;   /* 0x4 */
    s16 f6;   /* 0x6 */
} Foo_80134510;
typedef struct {
    u16 f0;   /* 0x0 */
    u16 f2;   /* 0x2 */
    u16 f4;   /* 0x4 */
    s16 f6;   /* 0x6 */
} Foo_80134510_80134510;
typedef struct {
    short v0, v1, v2, pad06, w0, w1, w2, pad0E;          /* 0x00..0x0F */
    short v3, v4, v5, pad16, w3, w4, w5, pad1E;          /* 0x10..0x1F */
    u8 c00, c01, c02, pad23;                             /* 0x20 */
    u8 c10, c11, c12, pad27;                             /* 0x24 */
    u8 c20, c21, c22, pad2B;                             /* 0x28 */
    u8 c30, c31, c32, pad2F;                             /* 0x2C */
    int tag;                                             /* 0x30 -> struct size 0x34; tag lands at sp+0x40 */
} Frame_80166690;
typedef struct {
    short v0, v1, v2, pad06, w0, w1, w2, pad0E;          /* 0x00..0x0F */
    short v3, v4, v5, pad16, w3, w4, w5, pad1E;          /* 0x10..0x1F */
    u8 c00, c01, c02, pad23;                             /* 0x20 */
    u8 c10, c11, c12, pad27;                             /* 0x24 */
    u8 c20, c21, c22, pad2B;                             /* 0x28 */
    u8 c30, c31, c32, pad2F;                             /* 0x2C */
    int tag;                                             /* 0x30 -> struct size 0x34; tag lands at sp+0x40 */
} Frame_80166690_80166690;
typedef struct { u16 h; } H16;
typedef struct { s16 x; s16 y; } Hw4;
typedef struct { char _b[8]; } M8;
typedef struct { char _b[8]; } M8_801312D0;
typedef struct { s16 m[3][3]; s32 t[3]; } MATRIX2;
typedef struct { short m[3][3]; short pad; s32 t[3]; } MATRIX_8016E7C8;
typedef struct { s16 m[3][3]; s16 pad; s32 t[3]; } MATRIX_8017E6D8;
typedef struct { s16 m[3][3]; s16 pad; s32 t[3]; } MTX_801749C8;
typedef struct { s16 m[3][3]; s16 pad; s32 t[3]; } MTX_8017BB34;
typedef struct { int a[8]; } MTX_L1;
typedef struct Map_80133AB0 {
    u16 ox;       /* 0x00 */
    u16 oy;       /* 0x02 */
    u16 w;        /* 0x04 */
    u16 h;        /* 0x06 */
    u16 *cells;   /* 0x08 */
    void *p0C;    /* 0x0C */
    void *p10;    /* 0x10 */
    u8  *p14;     /* 0x14 */
    u8  *p18;     /* 0x18 */
    u8  *p1C;     /* 0x1C */
} Map_80133AB0;
typedef struct { s32 m[8]; } Mat_80167540;
struct Src_80167540 {
    u8 pad0[0x34];
    Mat_80167540 mat;          /* 0x34 */
};
struct Node_80167540 {
    /* 0x0 */ u16 unk0;
    u8 pad2[0x4];
    /* 0x6 */ s16 unk6;
    u8 pad8[0x2];
    /* 0xA */ s16 unkA;
    u8 padC[0x2];
    /* 0xE */ s16 unkE;
    u8 pad10[0x10];
    /* 0x20 */ struct Src_80167540 *unk20;
    u8 pad24[0x28];
    /* 0x4C */ struct Sub2_80167540 *unk4C;
};
struct Entity_80167540 {
    /* 0x0 */ s16 unk0;
    /* 0x2 */ u16 unk2;
    u8 pad4[0xC];
    /* 0x10 */ s16 unk10;
    /* 0x12 */ s16 unk12;
    u8 pad14[0x8];
    /* 0x1C */ s32 unk1C;
    u8 pad20[0x10];
    /* 0x30 */ s32 unk30;
    /* 0x34 */ struct Node_80167540 *unk34;
    /* 0x38 */ Mat_80167540 mat;
};
typedef struct Mat_8016A73C { int w[8]; } Mat_8016A73C;
typedef struct {
    s16 m[9];    /* 0x00 */
    s16 pad;     /* 0x12 */
    s32 t[3];    /* 0x14, 0x18, 0x1c */
    s32 rest[8]; /* 0x20..0x3f */
} Mtx;
typedef struct {
    s16 m[9];    /* 0x00 */
    s16 pad;     /* 0x12 */
    s32 t[3];    /* 0x14, 0x18, 0x1c */
    s32 rest[8]; /* 0x20..0x3f */
} Mtx_8016BFD0;
typedef struct { u8 pad0[0x12]; u16 unk12; } Obj20_80178D40;
typedef struct Actor_80178D40 {
    s16 unk0;
    s16 unk2;
    s16 unk4;
    u16 unk6;
    s16 unk8;
    u16 unkA;
    s16 unkC;
    u16 unkE;
    u8 pad10[0x20 - 0x10];
    Obj20_80178D40 *unk20;
    u8 pad24[0x34 - 0x24];
    s16 unk34;
    u8 pad36[0xD4 - 0x36];
    struct Actor_80178D40 *unkD4;
    s32 unkD8;
    s32 unkDC[7];
    s32 unkF8;
    u8 padFC[0x10A - 0xFC];
    s16 unk10A;
} Actor_80178D40;
typedef struct Obj_8016AB6C {
    s32 unk0;
    s32 unk4;
    u8  pad8[0xE - 0x8];
    s16 unkE;
    u8  pad10[0x24 - 0x10];
    u8  unk24, unk25, unk26, unk27;
    u8  pad28[0x2E - 0x28];
    s16 unk2E;
    s16 unk30;
} Obj_8016AB6C;
typedef struct Ent_8016AB6C {
    u16 unk0, unk2, unk4, unk6, unk8, unkA, unkC, unkE;
    s32 unk10, unk14, unk18, unk1C;
    Obj_8016AB6C *unk20;
    s16 unk24, unk26, unk28, unk2A;
    s32 unk2C;
    s32 unk30;
} Ent_8016AB6C;
typedef struct { char pad[0x90]; Elem_8012ACE0 *list; } Owner_8012ACE0;
typedef struct { char pad[0x90]; Elem_8012ACE0_8012ACE0 *list; } Owner_8012ACE0_8012ACE0;
typedef struct { u32 addr : 24; u8 len; } PTag_8018F694;
typedef struct { s16 x, y; } Pair;
typedef struct { s16 x, y; } Pair_8013AD38;
typedef struct { u32 xx, yy, zz; u32 nprim; u32 *prim; } Part;
typedef struct { u32 tag, rgbc; s16 x0, y0, x1, y1, x2, y2; } PolyF3;
typedef struct { u32 tag, rgbc; s16 x0, y0, x1, y1, x2, y2, x3, y3; } PolyF4;
typedef struct { u32 tag, rgbc; s16 x0, y0; u32 uvc0; s16 x1, y1; u32 uvp1; s16 x2, y2; u16 uv2, p2; } PolyFT3;
typedef struct { u32 tag, rgbc; s16 x0, y0; u32 uvc0; s16 x1, y1; u32 uvp1; s16 x2, y2; u16 uv2, p2; s16 x3, y3; u16 uv3, p3; } PolyFT4;
typedef struct { u16 f0; s16 f2; } Prim4;
typedef struct { s32 a, b, c; } Rec12;
typedef struct { s32 f0; u32 *f4; s32 f8; s32 fC; s32 f10; } Rec20;
typedef struct { s32 a, b; s8 c; } __attribute__((packed, aligned(1))) Rec9;
typedef struct { u16 h[6]; } Rec_80166690;
typedef struct { u16 h[6]; } Rec_80166690_80166690;
typedef struct {
    /* 0x00 */ u16 f0;
    /* 0x02 */ s16 f2;
    /* 0x04 */ s16 f4;
    /* 0x06 */ s16 f6;
    /* 0x08 */ s16 f8;
    /* 0x0A */ s16 fa;
    /* 0x0C */ s16 fc;
    /* 0x0E */ s16 fe;
    /* 0x10 */ s16 f10;
    /* 0x12 */ s16 f12;
    /* 0x14 */ s16 f14;
} S0;
typedef struct {
    /* 0x00 */ u16 f0;
    /* 0x02 */ s16 f2;
    /* 0x04 */ s16 f4;
    /* 0x06 */ s16 f6;
    /* 0x08 */ s16 f8;
    /* 0x0A */ s16 fa;
    /* 0x0C */ s16 fc;
    /* 0x0E */ s16 fe;
    /* 0x10 */ s16 f10;
    /* 0x12 */ s16 f12;
    /* 0x14 */ s16 f14;
} S0_801347A0;
typedef struct { char s[10]; } S10;
typedef struct { char s[10]; } S10_80136C90;
typedef struct {
    unsigned short field0;   /* 0x00  D_80115118 */
    unsigned char  _pad[0xAE];
    int            arrB0[128];/* 0xB0 */
} S115118;
typedef struct { unsigned char b[8]; } S8_8017B8E8;
typedef struct { u8 b[8]; } S8_80184F08;
typedef struct { u8 b[9]; } S9;
typedef struct { s16 vx, vy, vz, pad; } SV3_80178D40;
typedef struct { s16 vx, vy, vz, pad; } SV4_801749C8;
typedef struct { s16 a, b, c, d; } SV4_8017B368;
typedef struct { SV4_8017B368 x, y; } Pair16;
typedef struct { SV4_8017B368 x, y; } Pair16_8017B368;
typedef struct { s16 a, b, c, d; } SV4_8017BB34;
typedef struct { short vx, vy, vz, pad; } SVECTOR;
typedef struct { s16 vx, vy, vz, pad; } SVECTOR2;
typedef struct { short vx, vy, vz, pad; } SVECTOR_8016E7C8;
typedef struct { u16 vx, vy, vz, pad; } SVECTOR_8017E6D8;
typedef struct { short vx, vy, vz, pad; } SVECTOR_80184F08;
typedef struct { s16 x, y, z, pad; } SVEC_80167AE0;
typedef struct { s16 x, y, z, pad; } SVEC_8016A290;
typedef struct { short vx, vy, vz, pad; } SVEC_L1;
typedef struct {
    /* 0x0 */ u16 f0;
    /* 0x2 */ u16 f2;
    /* 0x4 */ u16 f4;
    /* 0x6 */ u16 f6;
} SVec;
typedef struct {
    /* 0x0 */ u16 f0;
    /* 0x2 */ u16 f2;
    /* 0x4 */ u16 f4;
    /* 0x6 */ u16 f6;
} SVec_801347A0;
typedef struct SVec_8016AB6C {
    s16 vx, vy, vz, pad;
} SVec_8016AB6C;
typedef struct { char pad_8013BC7C[0x68]; s32 f68; } S_8013BC7C;
typedef struct { B8_80165140 a; B4 b; s32 used; } Slot;
typedef struct { B8_80165140 a; B4_80165140 b; s32 used; } Slot_80165140;
typedef struct { u8 f0; u8 pad[0xc3]; } Slot_998;
typedef struct {
    s16 f0;
    s16 f2;
    s16 f4;
    s16 f6;
} Stk801395D4;
typedef struct SubB_8016A73C { char pad[0x20]; int unk20; } SubB_8016A73C;
typedef struct SubA_8016A73C { char pad[0x34]; SubB_8016A73C *unk34; } SubA_8016A73C;
typedef struct Obj_8016A73C {
    short unk0;
    short unk2;
    short unk4;
    short unk6;
    short unk8;
    short unkA;
    short unkC;
    short unkE;
    char pad10[0x24];   /* 0x10 .. 0x33 */
    SubA_8016A73C *unk34;         /* 0x34 */
    Mat_8016A73C mat;             /* 0x38 .. 0x57 */
} Obj_8016A73C;
typedef struct {
    u8   pad00[0x12];
    u16  unk12;              /* 0x12 */
} Sub_80155800_80155800;
typedef struct {
    u8            pad00[0x20];
    Sub_80155800_80155800 *unk20;     /* 0x20 */
    u8            pad24[0x44 - 0x24];
    s32           unk44;     /* 0x44 */
    u8            pad48[0xB8 - 0x48];
    u16           unkB8;     /* 0xB8 */
    u8            padBA[0x1A8 - 0xBA];
    u8            unk1A8;    /* 0x1A8 */
    u8            unk1A9;    /* 0x1A9 */
    u8            unk1AA;    /* 0x1AA */
    u8            pad1AB[0x1C0 - 0x1AB];
    u8            unk1C0;    /* 0x1C0 */
    u8            pad1C1[0x234 - 0x1C1];
    u8            unk234;    /* 0x234 */
} Ent_80155800_80155800;
typedef struct {
    u8  b0;
    u8  b1;
    u8  b2;
    u8  type;
    u32 w1;
    u32 w2;
} T3Reloc;
typedef struct {
    u32 addr : 24;
    u8 len;
    u32 code0;
} TPage_8018F694;
typedef struct {
    u16 f00, f02, f04, f06;
    s16 f08;
    u16 f0a, f0c, f0e, f10, f12, f14, f16;
    u8  f18, f19, f1a, f1b, f1c, f1d, f1e, f1f, f20, f21, f22, f23;
    u32 f24;
} Thing_80168828;
typedef struct {
    u16 f00, f02, f04, f06;
    s16 f08;
    u16 f0a, f0c, f0e, f10, f12, f14, f16;
    u8  f18, f19, f1a, f1b, f1c, f1d, f1e, f1f, f20, f21, f22, f23;
    u32 f24;
} Thing_80168828_80168828;
typedef struct { s16 f0, f1, f2, f3, f4, f5; } TrailEntry;
typedef struct { u8 flag, idx, count, timer; TrailEntry e[16]; } Trail;
typedef struct { u16 vx, vy, vz, pad; } UVEC_8018F694;
typedef struct { s16 x, y, z; } V3;
typedef struct { s32 vx, vy, vz; } VECTOR;
typedef struct { s16 vx, vy, vz, pad; } Vec16;
typedef struct { s32 vx, vy, vz, pad; } Vec32;
typedef struct { s16 x, y, z; } Vec3_8016BFD0;
typedef struct {
    u16 x;
    s16 y;
    u16 z;
} Vec3h;
typedef struct { s16 x, y, z; } Vec3s;
typedef struct { char b[4]; } W;
typedef struct { char b[4]; } W_8016BFD0;
typedef struct {
    u16 x, y, z, xpad;      /* 0x00 : in  -> sp+0x20 */
    u16 vx, vy, vz, vpad;   /* 0x08 : out -> sp+0x28 */
} Work8016;
typedef struct {
    u16 x, y, z, xpad;      /* 0x00 : in  (Pos800D20C0, padded to 8) -> sp+0x20 */
    u16 vx, vy, vz, vpad;   /* 0x08 : out (SVECTOR)                  -> sp+0x28 */
    s32 dead[8];            /* 0x10 : reserved, unaccessed           -> sp+0x30..0x4F */
} Work8017;
typedef void (*code)(unsigned short *);
struct Fr {
    u8   matrix[0x20];                    /* 0x00 -> sp+0x10 */
    SVEC_80167AE0 v[4];                            /* 0x20 -> sp+0x30 */
    struct { u8 r, g, b, pad; } col[4];   /* 0x40 -> sp+0x50 */
    u32  code;                            /* 0x50 -> sp+0x60 */
};
struct Fr_80167AE0 {
    u8   matrix[0x20];                    /* 0x00 -> sp+0x10 */
    SVEC_80167AE0 v[4];                            /* 0x20 -> sp+0x30 */
    struct { u8 r, g, b, pad; } col[4];   /* 0x40 -> sp+0x50 */
    u32  code;                            /* 0x50 -> sp+0x60 */
};
struct Fr_8016A290 {
    SVEC_8016A290 center;                          /* 0x00 -> sp+0x10 */
    SVEC_8016A290 diff;                            /* 0x08 -> sp+0x18 */
    s32  pos[3];                          /* 0x10 -> sp+0x20 */
    s32  _pad1c;                          /* 0x1C -> sp+0x2C */
    s16  mtx[32];                         /* 0x20 -> sp+0x30 */
    SVEC_8016A290 v[4];                            /* 0x60 -> sp+0x70 */
    struct { u8 r, g, b, pad; } col[4];   /* 0x80 -> sp+0x90 */
    u32  code;                            /* 0x90 -> sp+0xA0 */
};
typedef struct {
    u32 addr : 24;
    u8 len;
    u8 r0, g0, b0, code;
    s16 x0, y0, x1, y1;
} LineF2_8018F694;
typedef struct { u32 addr : 24; u32 len : 8; u8 r0, g0, b0, code; } P_TAG_8013DD68;
typedef struct { s16 ax, ay, a04, a06, bx, by, b0c, b0e, cx, cy, c14, c16, dx, dy, d1c, d1e, u0, v0, u1, v1, u2, v2, u3, v3; u8 r, g, b, pad33; s32 tag; u8 code, pad39, pad3a, pad3b; s32 pad3c; } Prim_B234;
#endif /* BFM_ENGINE_TYPES_H */

/* Phase-29 crack-wave lift (func_8012956C family) */
typedef struct { s32 a, b, c, d; } Blk16_956C;
typedef struct {
    u8 pad0[0x1C];
    s16 f1C;
    s16 f1E;
    u8 pad20[0x14];
    u16 f34;
    u16 f36;
    u16 f38;
    u16 f3A;
    u8 pad3C[2];
    s16 f3E;
    u16 f40;
    u16 f42;
    u8 pad44[0x10];
} Ent_956C;


/* Phase-29 crack-wave lift (func_801670E4 family) */
typedef struct { s16 x, y, z, pad; } SVec_801670E4;   /* 8 bytes */
typedef struct {
    /* 0x00 */ u16 cx, cy, cz;
    /* 0x06 */ u16 _p06;
    /* 0x08 */ u16 a8[4];
    /* 0x10 */ s32 pos[3];
    /* 0x1C */ s32 _p1C;
    /* 0x20 */ SVec_801670E4 v[4];
    /* 0x40 */ struct { u8 r, g, b, cd; } col[4];
    /* 0x50 */ u32 code;
    /* 0x54 */ s32 _p54;
    /* 0x58 */ u8 m1[0x20];
    /* 0x78 */ u8 m2[0x20];
} Fr_801670E4;   /* 0x98 bytes -> sp+0x10 .. sp+0xA8 */


/* Phase-29 crack-wave lift (func_8016CBC0 family) */
typedef struct
{
  u16 h[6];
} Rec_8016CBC0;
typedef struct
{
  u8 f0;
  u8 f1;
  u8 f2;
  u8 f3;
  Rec_8016CBC0 ent[16];
} Blk_8016CBC0;
typedef struct
{
  s16 x;
  s16 y;
  s16 z;
  s16 pad;
} SVEC_8016CBC0;
typedef struct
{
  u8 r;
  u8 g;
  u8 b;
  u8 pad;
} CLR_8016CBC0;
typedef struct
{
  SVEC_8016CBC0 v[4];
  CLR_8016CBC0 col[4];
  s32 tag;
} Poly_8016CBC0;
typedef struct
{
  s32 w[8];
} Mtx8_8016CBC0;

/* Phase-29 decl-normalize+lift (func_8013D53C family) */
typedef struct {
    u16 cmd;        /* 0x0 */
    u16 pad2;       /* 0x2 */
    u16 pad4;       /* 0x4 */
    u16 pad6;       /* 0x6 */
    s16 w;          /* 0x8 */
    s16 h;          /* 0xA */
    u16 *data;      /* 0xC */
} Cmd_8013D53C;              /* 0x10 */
