/* func_80183814 -- 5,122 instructions, overlay ov_SC07_006.  21-case jr jump-table
 * state machine on *(u16*)(a0+0x34).  ROUND-1 DRAFT (2026-07-26).
 *
 * MEASURED, tools/match_one.py, no edits:
 *   DIFF  func_80183814   mine=5127 ins, target=5122 ins, 4622 mismatched
 * match_one is strictly index-wise, so the +5 length delta smears the whole
 * tail.  Under a difflib-aligned comparison the real state is:
 *   register-BLIND (structure only):  36 of 5122 target ins unmatched  (99.3% exact)
 *   register-sensitive:             1201 of 5122
 * Frame: mine -256 / 10 saved regs;  target -0xF8 (-248) / 8 saved regs.
 * The 216-byte args+locals area is BYTE-EXACT; the only frame delta is the 2 extra
 * callee-saved registers (8 bytes + alignment).
 *
 * DECODE IS DONE AND IS NOT THE BLOCKER.  Every one of the 36 structural residuals
 * is a *consequence* of one global register-allocation fork (see the report):
 * in cases 0 and 3 gcc CSEs &D_8018E27C/&D_8018E288/&D_8018E294 (+0x30) across the
 * two func_8017D8A4 groups that share a basic block, which consumes 2 callee-saved
 * registers the target spends on real variables.  The target rematerialises them.
 *
 * BYTE-VERIFIED LEVERS APPLIED (each measured; drop-one results in the report):
 *  1. The 35x spawn template is ONE 72-instruction body parameterised only by
 *     (KIND, START, BOUND); the struct member offset is always KIND*4 and the array
 *     base is always &D_801F61C0[START], with prev.BOUND == next.START (a single
 *     running index over a 16-element array, segmented by kind).  Verified identical
 *     to target instance @801880C8 for all 67 non-prologue instructions.
 *     Three sub-levers, each load-bearing:
 *       a. running POINTER walk with the counter initialised FIRST:
 *          for (s4 = START, q = &D_801F61C0[START]; s4 < BOUND; s4++, q++)
 *          Array indexing D_801F61C0[s4] does NOT strength-reduce under -G0 (the
 *          MIPS lo_sum address form blocks loop.c's giv): +3 ins/instance = +105.
 *       b. rand() % (u32)s0  ->  divu.  A signed % emits div plus gcc's
 *          INT_MIN/-1 overflow trap: +5 ins/instance = +175.
 *       c. (s32)((u8 *)p + ((X) + 0xC)).  Spelling it (s32)p + (X + 0xC) lets
 *          combine reassociate to (p + 0xC) + X, folding an instruction away and
 *          filling the bne delay slot: -1 ins/instance.
 *  2. NO dead `pad[32]` local.  The prior handoff assumed one to reach frame 0xF8;
 *     it is wrong.  Those 132 bytes are gcc's own spill area.  Removing pad makes
 *     the args+locals area exactly 216 bytes == the target's.
 *  3. The morph/lerp block (cases 6, 9, 11): (a) msb/msa must be assigned BEFORE
 *     the `if (mp[1] == 1)` (after costs 8 ins/case); (b) the loop must walk COPIES
 *     of the two source pointers (`pa = msa; pb = msb;` then walk pa/pb, leaving
 *     msa/msb alone) -- that reproduces the target's giv-init `addu` copies and
 *     takes cases 6 and 11 from 8 and 7 structural diffs to ZERO.
 *  4. Two divisors, not one: the cases 0/1/3/4 audio ramp divides by 455
 *     (magic 0x90090091); the cases 8/9 ramp divides by 409 (magic 0xA03C1689).
 *  5. Case 12's tail was incomplete in the prior recon -- it cross-jumps into
 *     case 14's tail and must also carry the 0x400 store and func_8002D4C8(0xBBD,0).
 *
 * NO __asm__ REGISTER PINS ARE USED HERE.  A diagnostic pin (a0 -> $s2) is recorded
 * in the report: it is a hand-placed dial, not plausible original source, and it only
 * halves the residual (4317 -> 4241 under match_one) without fixing the frame.
 *
 * Generated by .run/giants/s20_g14_build.py from s20_g14_parts.py + s20_g14_mktmpl.py;
 * edit those and regenerate rather than editing this file by hand.
 */
#include "common.h"

extern s32 func_8004787C(s32 a0);
extern void func_8017FDF8(s32 a0);
extern void func_8017F9AC(s32 a0, void *a1);
extern void func_8017D8A4(s32 a0, void *a1, void *a2, s32 a3, s32 a4);
extern void func_800599B8(void *a0, s32 a1);
extern s32 func_8012C658(s32 a0, s32 a1, s32 a2);
extern void func_8002D4C8(s32 a0, s32 a1);
extern void func_8017F5D4(s32 a0);
extern void func_801805D4(s32 a0, void *a1);
extern void func_8001C214(s32 a0, void *a1);
extern void func_8001D0E8(s32 a0, s32 a1, s32 a2);
extern void func_8012A828(s32 a0, void *a1);
extern void func_80016224(s32 a0, s32 a1);
extern void func_8012EC04(s32 a0, s32 a1, s32 *a2);
extern void func_8012F14C(s32 *a0, s32 a1, s16 *a2);
extern s32 func_8012C51C(s16 *a0, s32 a1);
extern s32 rand(void);
extern s32 func_80178970(s32 a0);
extern void func_80178D18(s32 a0);
extern void func_801802EC(s32 a0);
extern void func_80180924(s32 a0);
extern void func_80180CFC(s32 a0, void *a1);
extern void func_80181148(s32 a0);
extern void func_8018163C(s32 a0);
extern void func_80181924(s32 a0, void *a1);
extern void func_80182268(s32 a0, s32 a1);
extern void func_801823F8(s32 a0);
extern void func_801826E0(s32 a0, s32 a1);
extern void func_801828A4(s32 a0);
extern void func_80182B8C(s32 a0, s32 a1);
extern void func_80181E64(s32 a0, s32 a1);
extern void func_80182000(s32 a0, s32 a1);
extern void func_80182158(s32 a0);
extern void func_80181C74(s32 a0, s32 a1);
extern void func_80182D4C(s32 a0, s32 a1);
extern void func_80128EA8(s32 a0, s32 a1, void *a2);
extern s32 func_80143C74(s32 a0, s32 a1);

extern u8 D_8018E27C;
extern u8 D_8018E288;
extern u8 D_8018E294;
extern u8 D_8018E2A0;
extern u8 D_8018E2DC;
extern u8 D_8018E2E8;
extern u8 D_8018E2F4;
extern u8 D_8018E300;
extern u8 D_8018DFC0;
extern u8 D_8018DFC8;
extern u8 D_8018DFD0;
extern u8 D_8018DFD8;
extern u8 D_8018DFE0;
extern u8 D_8018DFE8;
extern u8 D_8018DFF0;
extern u8 D_8018DFF8;
extern u8 D_8018E000;
extern u8 D_8018E008;
extern u8 D_8018E010;
extern u8 D_8018E018;
extern s32 D_8018E034[];
extern u8 D_8018DF10;
extern s32 D_801BFCB4;
extern s32 D_801BFCBC;
extern s32 D_801BFCC4;
extern u8 D_801BF540;
extern u8 D_801BF588;
extern u8 D_801BFCCC;
extern s32 *D_801BF5CC;
extern u8 D_801BF630;
extern u8 D_801BFCDC;
extern u8 D_801BF658;
extern u8 D_801BFCE4;
extern u8 D_801BF68C;
extern u8 D_801BFCEC;
extern u8 D_801CAA38;
extern u8 D_8018E020;
extern u8 D_8018E028;
extern u8 D_8018E030;
extern u8 D_8018E3A8;
extern u8 D_801BF60C;
extern s32 D_801BFCD4;
extern s16 *D_801C1E14;
extern s16 *D_801C1E18;
extern u8 D_801BF6CC;
extern u8 D_801CA678;
extern s32 *D_801BF604;
extern s32 *D_801BF650;
extern s16 *D_801C1EA0;
extern s16 *D_801C1EA4;
extern s16 *D_801C1EA8;
extern s32 D_801F61C0[];

void func_80183814(void *a0) {
    s32 sp18[8];
    s16 sp38[4];
    s16 sp40[10];
    s32 s3;
    s32 s0;
    s32 s1;
    s32 s4;
    s32 s5;
    s32 c;
    s32 r;
    s32 t;
    s32 idx;
    s32 ok;
    s32 *p;
    s32 *q;

    s0 = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
    s3 = s0 + (func_8004787C(*(s16 *)((s32)a0 + 0xFE)) >> 4);
    *(u16 *)((s32)a0 + 0xFE) = (*(u16 *)((s32)a0 + 0xFE) + 0x300) & 0xFFF;
    if (*(u16 *)((s32)a0 + 0x34) < 0x11) {
        *(s32 *)((s32)a0 + 0x8) =
            (*(s16 *)((s32)a0 + 0x8A) << 16) +
            (func_8004787C(*(s16 *)((s32)a0 + 0x104)) << 7);
        *(u16 *)((s32)a0 + 0x104) = *(u16 *)((s32)a0 + 0x104) + 0x40;
    }

    switch (*(u16 *)((s32)a0 + 0x34)) {
    case 0:
        *(s16 *)((s32)a0 + 0xFC) = *(s16 *)((s32)a0 + 0xFC) + 8;
        func_8017F9AC(s3, a0);
        func_8017D8A4(D_801BFCB4 + 0x3C, &D_8018E27C, &D_8018E27C + 0x30, s3, 1);
        func_8017D8A4(D_801BFCB4 + 0x48, &D_8018E288, &D_8018E288 + 0x30, s3, 1);
        func_8017D8A4(D_801BFCB4 + 0x54, &D_8018E294, &D_8018E294 + 0x30, s3, 1);
        func_8017D8A4(D_801BFCB4 + 0x60, &D_8018E2A0, &D_8018E2A0 + 0x30, s3, 1);
        func_8017FDF8(func_8004787C(*(s16 *)((s32)a0 + 0xFC)));
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            t = (s16)(c / 455);
            if (t >= 10) {
                t = 9;
            }
            func_800599B8(&D_8018DFC0, D_8018E034[t]);
        }
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            t = (s16)(c / 455);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 9;
            func_800599B8(&D_8018DFC8, D_8018E034[idx]);
        }
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            t = (s16)(c / 455);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x12;
            func_800599B8(&D_8018DFD0, D_8018E034[idx]);
        }
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            t = (s16)(c / 455);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x1B;
            func_800599B8(&D_8018DFD8, D_8018E034[idx]);
        }
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            t = (s16)(c / 455);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x24;
            func_800599B8(&D_8018DFE0, D_8018E034[idx]);
        }
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            t = (s16)(c / 455);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x2D;
            func_800599B8(&D_8018DFE8, D_8018E034[idx]);
            ok = 1;
        } else {
            ok = 0;
        }
        if (ok != 0) {
            *(u16 *)((s32)a0 + 0x102) = *(u16 *)((s32)a0 + 0x102) + 0x1C7;
        }
        if (*(s16 *)((s32)a0 + 0xFC) != 0x200) {
            break;
        }
        s1 = 0;
        do {
            s0 = func_8012C658(0x3AC, 0, (s32)a0);
            if (s0 != 0) {
                *(u16 *)(s0 + 0xE) = *(u16 *)(s0 + 0xE) - 0x2D;
                *(u16 *)(s0 + 0xA) = *(u16 *)(s0 + 0xA) - 0x47;
                *(u16 *)(s0 + 0x6) = *(u16 *)(s0 + 0x6) - 5;
            }
            s1 += 1;
        } while (s1 < 0x10);
        func_8002D4C8(0xBBE, 0);
        func_8017F5D4(0x1000);
        func_8017D8A4(D_801BFCB4 + 0x3C, &D_8018E27C, &D_8018E27C + 0x30, 0x1000, 1);
        func_8017D8A4(D_801BFCB4 + 0x48, &D_8018E288, &D_8018E288 + 0x30, 0x1000, 1);
        func_8017D8A4(D_801BFCB4 + 0x54, &D_8018E294, &D_8018E294 + 0x30, 0x1000, 1);
        func_8017D8A4(D_801BFCB4 + 0x60, &D_8018E2A0, &D_8018E2A0 + 0x30, 0x1000, 1);
        *(u16 *)((s32)a0 + 0x34) = 1;
        func_801805D4(s3, a0);
        func_8001C214(*(s32 *)((s32)a0 + 0x20), &D_801BF540);
        func_8001D0E8(*(s32 *)((s32)a0 + 0x20), 0x280, 0x1E0);
        *(s16 *)(*(s32 *)((s32)a0 + 0x20) + 0x12) = 0x400;
        func_8012A828((s32)a0, &D_801BFCBC);
        func_8017D8A4(D_801BFCBC + 0x3C, &D_8018E27C, &D_8018E27C + 0x30, s3, 1);
        func_8017D8A4(D_801BFCBC + 0x48, &D_8018E288, &D_8018E288 + 0x30, s3, 1);
        func_8017D8A4(D_801BFCBC + 0x54, &D_8018E294, &D_8018E294 + 0x30, s3, 1);
        break;
    case 1:
        *(s16 *)((s32)a0 + 0xFC) = *(s16 *)((s32)a0 + 0xFC) + 8;
        func_801805D4(s3, a0);
        func_8017D8A4(D_801BFCBC + 0x3C, &D_8018E27C, &D_8018E27C + 0x30, s3, 1);
        func_8017D8A4(D_801BFCBC + 0x48, &D_8018E288, &D_8018E288 + 0x30, s3, 1);
        func_8017D8A4(D_801BFCBC + 0x54, &D_8018E294, &D_8018E294 + 0x30, s3, 1);
        func_8017FDF8(func_8004787C(*(s16 *)((s32)a0 + 0xFC)));
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            t = (s16)(c / 455);
            if (t >= 10) {
                t = 9;
            }
            func_800599B8(&D_8018DFC0, D_8018E034[t]);
        }
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            t = (s16)(c / 455);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 9;
            func_800599B8(&D_8018DFC8, D_8018E034[idx]);
        }
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            t = (s16)(c / 455);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x12;
            func_800599B8(&D_8018DFD0, D_8018E034[idx]);
        }
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            t = (s16)(c / 455);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x1B;
            func_800599B8(&D_8018DFD8, D_8018E034[idx]);
        }
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            t = (s16)(c / 455);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x24;
            func_800599B8(&D_8018DFE0, D_8018E034[idx]);
        }
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            t = (s16)(c / 455);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x2D;
            func_800599B8(&D_8018DFE8, D_8018E034[idx]);
            ok = 1;
        } else {
            ok = 0;
        }
        if (ok != 0) {
            *(u16 *)((s32)a0 + 0x102) = *(u16 *)((s32)a0 + 0x102) + 0x1C7;
        }
        if (*(s16 *)((s32)a0 + 0xFC) < 0x400) {
            break;
        }
        *(u16 *)((s32)a0 + 0x34) = 2;
        *(s32 *)((s32)a0 + 0x1C) = 0xA;
        func_801802EC(0x1000);
        func_8017D8A4(D_801BFCBC + 0x3C, &D_8018E27C, &D_8018E27C + 0x30, 0x1000, 1);
        func_8017D8A4(D_801BFCBC + 0x48, &D_8018E288, &D_8018E288 + 0x30, 0x1000, 1);
        func_8017D8A4(D_801BFCBC + 0x54, &D_8018E294, &D_8018E294 + 0x30, 0x1000, 1);
        func_8017FDF8(0x1000);
        break;
    case 2:
        if (*(s32 *)((s32)a0 + 0x1C) < 7) {
            func_80016224(0xFF, 0);
        }
        if ((*(s32 *)((s32)a0 + 0x1C) = *(s32 *)((s32)a0 + 0x1C) - 1) != 0) {
            break;
        }
        *(u16 *)((s32)a0 + 0x34) = 3;
        *(s16 *)((s32)a0 + 0xFC) = 0;
        *(u16 *)((s32)a0 + 0x102) = 0x1C7;
        func_8002D4C8(0xBB6, 0);
        break;
    case 3:
        *(s16 *)((s32)a0 + 0xFC) = *(s16 *)((s32)a0 + 0xFC) + 8;
        func_80180CFC(s3, a0);
        func_8017D8A4(D_801BFCBC + 0x84, &D_8018E2DC, &D_8018E2DC + 0x30, s3, 1);
        func_8017D8A4(D_801BFCBC + 0x90, &D_8018E2E8, &D_8018E2E8 + 0x30, s3, 1);
        func_8017D8A4(D_801BFCBC + 0x9C, &D_8018E2F4, &D_8018E2F4 + 0x30, s3, 1);
        func_8017D8A4(D_801BFCBC + 0xA8, &D_8018E300, &D_8018E300 + 0x30, s3, 1);
        func_80181148(func_8004787C(*(s16 *)((s32)a0 + 0xFC)));
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            t = (s16)(c / 455);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x36;
            func_800599B8(&D_8018DFF0, D_8018E034[idx]);
        }
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            t = (s16)(c / 455);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x3F;
            func_800599B8(&D_8018DFF8, D_8018E034[idx]);
        }
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            t = (s16)(c / 455);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x48;
            func_800599B8(&D_8018E000, D_8018E034[idx]);
        }
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            t = (s16)(c / 455);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x51;
            func_800599B8(&D_8018E008, D_8018E034[idx]);
        }
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            t = (s16)(c / 455);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x5A;
            func_800599B8(&D_8018E010, D_8018E034[idx]);
        }
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            t = (s16)(c / 455);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x63;
            func_800599B8(&D_8018E018, D_8018E034[idx]);
            ok = 1;
        } else {
            ok = 0;
        }
        if (ok != 0) {
            *(u16 *)((s32)a0 + 0x102) = *(u16 *)((s32)a0 + 0x102) + 0x1C7;
        }
        if (*(s16 *)((s32)a0 + 0xFC) < 0x200) {
            break;
        }
        s1 = 0;
        do {
            s0 = func_8012C658(0x3AC, 0, (s32)a0);
            if (s0 != 0) {
                *(u16 *)(s0 + 0xE) = *(u16 *)(s0 + 0xE) + 0x2D;
                *(u16 *)(s0 + 0xA) = *(u16 *)(s0 + 0xA) - 0x47;
                *(u16 *)(s0 + 0x6) = *(u16 *)(s0 + 0x6) - 5;
            }
            s1 += 1;
        } while (s1 < 0x10);
        func_8002D4C8(0xBBE, 0);
        func_80180924(0x1000);
        func_8017D8A4(D_801BFCBC + 0x84, &D_8018E2DC, &D_8018E2DC + 0x30, 0x1000, 1);
        func_8017D8A4(D_801BFCBC + 0x90, &D_8018E2E8, &D_8018E2E8 + 0x30, 0x1000, 1);
        func_8017D8A4(D_801BFCBC + 0x9C, &D_8018E2F4, &D_8018E2F4 + 0x30, 0x1000, 1);
        func_8017D8A4(D_801BFCBC + 0xA8, &D_8018E300, &D_8018E300 + 0x30, 0x1000, 1);
        *(u16 *)((s32)a0 + 0x34) = 4;
        func_80181924(s3, a0);
        func_8001C214(*(s32 *)((s32)a0 + 0x20), &D_801BF588);
        func_8001D0E8(*(s32 *)((s32)a0 + 0x20), 0x280, 0x1E0);
        *(s16 *)(*(s32 *)((s32)a0 + 0x20) + 0x12) = 0x400;
        func_8012A828((s32)a0, &D_801BFCC4);
        func_8017D8A4(D_801BFCC4 + 0x84, &D_8018E2DC, &D_8018E2DC + 0x30, s3, 1);
        func_8017D8A4(D_801BFCC4 + 0x90, &D_8018E2E8, &D_8018E2E8 + 0x30, s3, 1);
        func_8017D8A4(D_801BFCC4 + 0x9C, &D_8018E2F4, &D_8018E2F4 + 0x30, s3, 1);
        break;
    case 4:
        *(s16 *)((s32)a0 + 0xFC) = *(s16 *)((s32)a0 + 0xFC) + 8;
        func_80181924(s3, a0);
        func_8017D8A4(D_801BFCC4 + 0x84, &D_8018E2DC, &D_8018E2DC + 0x30, s3, 1);
        func_8017D8A4(D_801BFCC4 + 0x90, &D_8018E2E8, &D_8018E2E8 + 0x30, s3, 1);
        func_8017D8A4(D_801BFCC4 + 0x9C, &D_8018E2F4, &D_8018E2F4 + 0x30, s3, 1);
        func_80181148(func_8004787C(*(s16 *)((s32)a0 + 0xFC)));
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            t = (s16)(c / 455);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x36;
            func_800599B8(&D_8018DFF0, D_8018E034[idx]);
        }
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            t = (s16)(c / 455);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x3F;
            func_800599B8(&D_8018DFF8, D_8018E034[idx]);
        }
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            t = (s16)(c / 455);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x48;
            func_800599B8(&D_8018E000, D_8018E034[idx]);
        }
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            t = (s16)(c / 455);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x51;
            func_800599B8(&D_8018E008, D_8018E034[idx]);
        }
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            t = (s16)(c / 455);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x5A;
            func_800599B8(&D_8018E010, D_8018E034[idx]);
        }
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            t = (s16)(c / 455);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x63;
            func_800599B8(&D_8018E018, D_8018E034[idx]);
            ok = 1;
        } else {
            ok = 0;
        }
        if (ok != 0) {
            *(u16 *)((s32)a0 + 0x102) = *(u16 *)((s32)a0 + 0x102) + 0x199;
        }
        if (*(s16 *)((s32)a0 + 0xFC) < 0x400) {
            break;
        }
        *(u16 *)((s32)a0 + 0x34) = 5;
        *(s32 *)((s32)a0 + 0x1C) = 0xA;
        func_8018163C(0x1000);
        func_8017D8A4(D_801BFCC4 + 0x84, &D_8018E2DC, &D_8018E2DC + 0x30, 0x1000, 1);
        func_8017D8A4(D_801BFCC4 + 0x90, &D_8018E2E8, &D_8018E2E8 + 0x30, 0x1000, 1);
        func_8017D8A4(D_801BFCC4 + 0x9C, &D_8018E2F4, &D_8018E2F4 + 0x30, 0x1000, 1);
        func_80181148(0x1000);
        break;
    case 5:
        if (*(s32 *)((s32)a0 + 0x1C) < 7) {
            func_80016224(0xFF, 0);
        }
        if ((*(s32 *)((s32)a0 + 0x1C) = *(s32 *)((s32)a0 + 0x1C) - 1) != 0) {
            break;
        }
        *(u16 *)((s32)a0 + 0x34) = 6;
        *(s16 *)((s32)a0 + 0xFC) = 0;
        func_8001C214(*(s32 *)((s32)a0 + 0x20), &D_801BF5CC);
        func_8001D0E8(*(s32 *)((s32)a0 + 0x20), 0x280, 0x1E0);
        *(s16 *)(*(s32 *)((s32)a0 + 0x20) + 0x12) = 0x400;
        func_8012A828((s32)a0, &D_801BFCCC);
        func_8012C658(0x3AC, 1, (s32)a0);
        *(u16 *)((s32)a0 + 0x102) = 0x1C7;
        func_8002D4C8(0xBB9, 0);
        func_8002D4C8(0xC6F, 0);
        break;
    case 6:
        *(s16 *)((s32)a0 + 0xFC) = *(s16 *)((s32)a0 + 0xFC) + 8;
        {
            s32 *mp;
            s16 *md;
            s16 *msa;
            s16 *msb;
            s32 mn;
            s16 *pa;
            s16 *pb;

            mp = D_801BF604;
            msb = D_801C1EA0;
            msa = D_801C1EA4;
            if (mp[1] == 1) {
                md = (s16 *)mp[3];
            } else {
                md = (s16 *)((u8 *)mp + ((((u32)mp[3] >> 2) << 2) + 0xC));
            }
            mn = mp[4];
            pa = msa;
            pb = msb;
            while (mn != 0) {
                md[0] = pb[0] + (((pa[0] - pb[0]) * s3) >> 12);
                md[1] = pb[1] + (((pa[1] - pb[1]) * s3) >> 12);
                md[2] = pb[2] + (((pa[2] - pb[2]) * s3) >> 12);
                pa += 4;
                pb += 4;
                md += 4;
                mn--;
            }
        }
        func_80181C74((s32)a0, s3);
        if (*(s16 *)((s32)a0 + 0xFC) < 0x400) {
            break;
        }
        *(u16 *)((s32)a0 + 0x34) = 7;
        *(s32 *)((s32)a0 + 0x1C) = 0xA;
        t = 0x1000;
        {
            s32 *mp;
            s16 *md;
            s16 *msa;
            s16 *msb;
            s32 mn;
            s16 *pa;
            s16 *pb;

            mp = D_801BF604;
            msb = D_801C1EA0;
            msa = D_801C1EA4;
            if (mp[1] == 1) {
                md = (s16 *)mp[3];
            } else {
                md = (s16 *)((u8 *)mp + ((((u32)mp[3] >> 2) << 2) + 0xC));
            }
            mn = mp[4];
            pa = msa;
            pb = msb;
            while (mn != 0) {
                md[0] = pb[0] + (((pa[0] - pb[0]) * t) >> 12);
                md[1] = pb[1] + (((pa[1] - pb[1]) * t) >> 12);
                md[2] = pb[2] + (((pa[2] - pb[2]) * t) >> 12);
                pa += 4;
                pb += 4;
                md += 4;
                mn--;
            }
        }
        func_80181C74((s32)a0, 0x1000);
        break;
    case 7:
        if (*(s32 *)((s32)a0 + 0x1C) < 7) {
            func_80016224(0xFF, 0);
        }
        if ((*(s32 *)((s32)a0 + 0x1C) = *(s32 *)((s32)a0 + 0x1C) - 1) != 0) {
            break;
        }
        *(u16 *)((s32)a0 + 0x34) = 8;
        *(s16 *)((s32)a0 + 0xFC) = 0;
        func_8002D4C8(0xBBC, 0);
        break;
    case 8:
        *(s16 *)((s32)a0 + 0xFC) = *(s16 *)((s32)a0 + 0xFC) + 8;
        func_80181E64(func_8004787C(*(s16 *)((s32)a0 + 0xFC)), (s32)a0);
        func_80182000((s32)a0, func_8004787C(*(s16 *)((s32)a0 + 0xFC)));
        func_80182158(func_8004787C(*(s16 *)((s32)a0 + 0xFC)));
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            t = (s16)(c / 409);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x7E;
            func_800599B8(&D_8018E030, D_8018E034[idx]);
        }
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            t = (s16)(c / 409);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x6C;
            func_800599B8(&D_8018E020, D_8018E034[idx]);
        }
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            t = (s16)(c / 409);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x75;
            func_800599B8(&D_8018E028, D_8018E034[idx]);
            ok = 1;
        } else {
            ok = 0;
        }
        if (ok != 0) {
            *(u16 *)((s32)a0 + 0x102) = *(u16 *)((s32)a0 + 0x102) + 0x199;
        }
        if (*(s16 *)((s32)a0 + 0xFC) < 0x200) {
            break;
        }
        func_8001C214(*(s32 *)((s32)a0 + 0x20), &D_801BF60C);
        func_8001D0E8(*(s32 *)((s32)a0 + 0x20), 0x280, 0x1E0);
        *(s16 *)(*(s32 *)((s32)a0 + 0x20) + 0x12) = 0x400;
        func_8012A828((s32)a0, &D_801BFCD4);
        func_8012C658(0x3AC, 2, (s32)a0);
        func_8012C658(0x3AC, 3, (s32)a0);
        *(u16 *)((s32)a0 + 0x34) = 9;
        func_80181E64(func_8004787C(*(s16 *)((s32)a0 + 0xFC)), (s32)a0);
        func_8017D8A4(D_801BFCD4, &D_8018E3A8, &D_8018E3A8 + 0xB4,
                      func_8004787C(*(s16 *)((s32)a0 + 0xFC)), 1);
        break;
    case 9:
        *(s16 *)((s32)a0 + 0xFC) = *(s16 *)((s32)a0 + 0xFC) + 8;
        func_80181E64(func_8004787C(*(s16 *)((s32)a0 + 0xFC)), (s32)a0);
        func_8017D8A4(D_801BFCD4, &D_8018E3A8, &D_8018E3A8 + 0xB4,
                      func_8004787C(*(s16 *)((s32)a0 + 0xFC)), 1);
        func_80182158(func_8004787C(*(s16 *)((s32)a0 + 0xFC)));
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            t = (s16)(c / 409);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x7E;
            func_800599B8(&D_8018E030, D_8018E034[idx]);
        }
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            t = (s16)(c / 409);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x6C;
            func_800599B8(&D_8018E020, D_8018E034[idx]);
        }
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            t = (s16)(c / 409);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x75;
            func_800599B8(&D_8018E028, D_8018E034[idx]);
            ok = 1;
        } else {
            ok = 0;
        }
        if (ok != 0) {
            *(u16 *)((s32)a0 + 0x102) = *(u16 *)((s32)a0 + 0x102) + 0x199;
        }
        if (*(s16 *)((s32)a0 + 0xFC) >= 0x400) {
            *(u16 *)((s32)a0 + 0x34) = 0xA;
            *(s32 *)((s32)a0 + 0x1C) = 0xA;
            t = 0x1000;
        {
            s32 *mp;
            s16 *md;
            s16 *msa;
            s16 *msb;
            s32 mn;
            s16 *pa;
            s16 *pb;

            mp = D_801BF5CC;
            msb = D_801C1E14;
            msa = D_801C1E18;
            if (mp[1] == 1) {
                md = (s16 *)mp[3];
            } else {
                md = (s16 *)((u8 *)mp + ((((u32)mp[3] >> 2) << 2) + 0xC));
            }
            mn = mp[4];
            pa = msa;
            pb = msb;
            while (mn != 0) {
                md[0] = pb[0] + (((pa[0] - pb[0]) * t) >> 12);
                md[1] = pb[1] + (((pa[1] - pb[1]) * t) >> 12);
                md[2] = pb[2] + (((pa[2] - pb[2]) * t) >> 12);
                pa += 4;
                pb += 4;
                md += 4;
                mn--;
            }
        }
            func_8017D8A4(D_801BFCD4, &D_8018E3A8, &D_8018E3A8 + 0xB4, 0x1000, 1);
            func_80182158(0x1000);
        }
        s0 = func_8012C658(0x3AC, 6, (s32)a0);
        if (s0 != 0) {
            *(u16 *)(s0 + 0x6) = *(u16 *)(s0 + 0x6) - 0x20;
            *(u16 *)(s0 + 0xA) = *(u16 *)(s0 + 0xA) - 0x140;
            *(u16 *)(s0 + 0xE) = *(u16 *)(s0 + 0xE) - 0x40;
            *(s16 *)(s0 + 0x12) = (rand() & 7) - 4;
            *(s16 *)(s0 + 0x16) = 0;
            *(s16 *)(s0 + 0x1A) = -((rand() & 7) + 0xA);
        }
        s0 = func_8012C658(0x3AC, 6, (s32)a0);
        if (s0 == 0) {
            break;
        }
        *(u16 *)(s0 + 0x6) = *(u16 *)(s0 + 0x6) - 0x20;
        *(u16 *)(s0 + 0xA) = *(u16 *)(s0 + 0xA) - 0x140;
        *(u16 *)(s0 + 0xE) = *(u16 *)(s0 + 0xE) + 0x40;
        *(s16 *)(s0 + 0x12) = (rand() & 7) - 4;
        *(s16 *)(s0 + 0x16) = 0;
        *(s16 *)(s0 + 0x1A) = (rand() & 7) + 0xA;
        break;
    case 10:
        if (*(s32 *)((s32)a0 + 0x1C) < 7) {
            func_80016224(0xFF, 0);
        }
        if ((*(s32 *)((s32)a0 + 0x1C) = *(s32 *)((s32)a0 + 0x1C) - 1) != 0) {
            break;
        }
        *(u16 *)((s32)a0 + 0x34) = 0xB;
        *(s16 *)((s32)a0 + 0xFC) = 0;
        func_8001C214(*(s32 *)((s32)a0 + 0x20), &D_801BF630);
        func_8001D0E8(*(s32 *)((s32)a0 + 0x20), 0x280, 0x1E0);
        *(s16 *)(*(s32 *)((s32)a0 + 0x20) + 0x12) = 0x400;
        func_8012A828((s32)a0, &D_801BFCDC);
        func_8002D4C8(0xBBF, 0);
        break;
    case 11:
        *(s16 *)((s32)a0 + 0xFC) = *(s16 *)((s32)a0 + 0xFC) + 0x10;
        t = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        {
            s32 *mp;
            s16 *md;
            s16 *msa;
            s16 *msb;
            s32 mn;
            s16 *pa;
            s16 *pb;

            mp = D_801BF650;
            msb = D_801C1EA4;
            msa = D_801C1EA8;
            if (mp[1] == 1) {
                md = (s16 *)mp[3];
            } else {
                md = (s16 *)((u8 *)mp + ((((u32)mp[3] >> 2) << 2) + 0xC));
            }
            mn = mp[4];
            pa = msa;
            pb = msb;
            while (mn != 0) {
                md[0] = pb[0] + (((pa[0] - pb[0]) * t) >> 12);
                md[1] = pb[1] + (((pa[1] - pb[1]) * t) >> 12);
                md[2] = pb[2] + (((pa[2] - pb[2]) * t) >> 12);
                pa += 4;
                pb += 4;
                md += 4;
                mn--;
            }
        }
        func_80182268((s32)a0, func_8004787C(*(s16 *)((s32)a0 + 0xFC)));
        if (*(s16 *)((s32)a0 + 0xFC) >= 0x400) {
            *(u16 *)((s32)a0 + 0x34) = 0xC;
            *(s32 *)((s32)a0 + 0x1C) = 0x1E;
            t = 0x1000;
        {
            s32 *mp;
            s16 *md;
            s16 *msa;
            s16 *msb;
            s32 mn;
            s16 *pa;
            s16 *pb;

            mp = D_801BF650;
            msb = D_801C1EA4;
            msa = D_801C1EA8;
            if (mp[1] == 1) {
                md = (s16 *)mp[3];
            } else {
                md = (s16 *)((u8 *)mp + ((((u32)mp[3] >> 2) << 2) + 0xC));
            }
            mn = mp[4];
            pa = msa;
            pb = msb;
            while (mn != 0) {
                md[0] = pb[0] + (((pa[0] - pb[0]) * t) >> 12);
                md[1] = pb[1] + (((pa[1] - pb[1]) * t) >> 12);
                md[2] = pb[2] + (((pa[2] - pb[2]) * t) >> 12);
                pa += 4;
                pb += 4;
                md += 4;
                mn--;
            }
        }
            func_80182268((s32)a0, 0x1000);
        }
        s5 = 0x8;
        func_8012EC04((s32)a0, 0x8, sp18);
        for (s4 = 0, q = &D_801F61C0[0]; s4 < 8; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0x8];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        break;
    case 12:
        if (*(s32 *)((s32)a0 + 0x1C) < 7) {
            func_80016224(0xFF, 0);
        }
        *(s32 *)((s32)a0 + 0x1C) = *(s32 *)((s32)a0 + 0x1C) - 1;
        s5 = 0x8;
        func_8012EC04((s32)a0, 0x8, sp18);
        for (s4 = 0, q = &D_801F61C0[0]; s4 < 8; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0x8];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        if (*(s32 *)((s32)a0 + 0x1C) != 0) {
            break;
        }
        *(u16 *)((s32)a0 + 0x34) = 0xD;
        *(s16 *)((s32)a0 + 0xFC) = 0;
        func_8001C214(*(s32 *)((s32)a0 + 0x20), &D_801BF658);
        func_8001D0E8(*(s32 *)((s32)a0 + 0x20), 0x280, 0x1E0);
        *(s16 *)(*(s32 *)((s32)a0 + 0x20) + 0x12) = 0x400;
        func_8012A828((s32)a0, &D_801BFCE4);
        func_8002D4C8(0xBBD, 0);
        break;
    case 13:
        *(s16 *)((s32)a0 + 0xFC) = *(s16 *)((s32)a0 + 0xFC) + 0x60;
        func_801823F8(func_8004787C(*(s16 *)((s32)a0 + 0xFC)));
        func_801826E0((s32)a0, func_8004787C(*(s16 *)((s32)a0 + 0xFC)));
        if (*(s16 *)((s32)a0 + 0xFC) >= 0x400) {
            *(u16 *)((s32)a0 + 0x34) = 0xE;
            *(s32 *)((s32)a0 + 0x1C) = 0x1E;
            func_801823F8(0x1000);
            func_801826E0((s32)a0, 0x1000);
        }
        s5 = 0x1;
        func_8012EC04((s32)a0, 0x1, sp18);
        for (s4 = 0, q = &D_801F61C0[0]; s4 < 4; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0x1];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        s5 = 0x2;
        func_8012EC04((s32)a0, 0x2, sp18);
        for (s4 = 4, q = &D_801F61C0[4]; s4 < 8; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0x2];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        s5 = 0xB;
        func_8012EC04((s32)a0, 0xB, sp18);
        for (s4 = 8, q = &D_801F61C0[8]; s4 < 12; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0xB];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        break;
    case 14:
        s5 = 0x1;
        func_8012EC04((s32)a0, 0x1, sp18);
        for (s4 = 0, q = &D_801F61C0[0]; s4 < 4; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0x1];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        s5 = 0x2;
        func_8012EC04((s32)a0, 0x2, sp18);
        for (s4 = 4, q = &D_801F61C0[4]; s4 < 8; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0x2];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        s5 = 0xB;
        func_8012EC04((s32)a0, 0xB, sp18);
        for (s4 = 8, q = &D_801F61C0[8]; s4 < 12; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0xB];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        if (*(s32 *)((s32)a0 + 0x1C) < 7) {
            func_80016224(0xFF, 0);
        }
        if ((*(s32 *)((s32)a0 + 0x1C) = *(s32 *)((s32)a0 + 0x1C) - 1) != 0) {
            break;
        }
        *(u16 *)((s32)a0 + 0x34) = 0xF;
        *(s16 *)((s32)a0 + 0xFC) = 0;
        func_8001C214(*(s32 *)((s32)a0 + 0x20), &D_801BF68C);
        func_8001D0E8(*(s32 *)((s32)a0 + 0x20), 0x280, 0x1E0);
        *(s16 *)(*(s32 *)((s32)a0 + 0x20) + 0x12) = 0x400;
        func_8012A828((s32)a0, &D_801BFCEC);
        func_8002D4C8(0xBBD, 0);
        break;
    case 15:
        *(s16 *)((s32)a0 + 0xFC) = *(s16 *)((s32)a0 + 0xFC) + 0x60;
        func_801828A4(func_8004787C(*(s16 *)((s32)a0 + 0xFC)));
        func_80182B8C((s32)a0, func_8004787C(*(s16 *)((s32)a0 + 0xFC)));
        if (*(s16 *)((s32)a0 + 0xFC) >= 0x400) {
            *(u16 *)((s32)a0 + 0x34) = 0x10;
            *(s32 *)((s32)a0 + 0x1C) = 0x1E;
            func_801828A4(0x1000);
            func_80182B8C((s32)a0, 0x1000);
        }
        s5 = 0x6;
        func_8012EC04((s32)a0, 0x6, sp18);
        for (s4 = 0, q = &D_801F61C0[0]; s4 < 4; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0x6];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        s5 = 0x7;
        func_8012EC04((s32)a0, 0x7, sp18);
        for (s4 = 4, q = &D_801F61C0[4]; s4 < 8; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0x7];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        s5 = 0x8;
        func_8012EC04((s32)a0, 0x8, sp18);
        for (s4 = 8, q = &D_801F61C0[8]; s4 < 12; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0x8];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        break;
    case 16:
        s5 = 0x6;
        func_8012EC04((s32)a0, 0x6, sp18);
        for (s4 = 0, q = &D_801F61C0[0]; s4 < 4; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0x6];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        s5 = 0x7;
        func_8012EC04((s32)a0, 0x7, sp18);
        for (s4 = 4, q = &D_801F61C0[4]; s4 < 8; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0x7];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        s5 = 0x8;
        func_8012EC04((s32)a0, 0x8, sp18);
        for (s4 = 8, q = &D_801F61C0[8]; s4 < 12; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0x8];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        if (*(s32 *)((s32)a0 + 0x1C) < 7) {
            func_80016224(0xFF, 0);
        }
        if ((*(s32 *)((s32)a0 + 0x1C) = *(s32 *)((s32)a0 + 0x1C) - 1) != 0) {
            break;
        }
        *(u16 *)((s32)a0 + 0x34) = 0x11;
        *(s16 *)((s32)a0 + 0xFC) = 0;
        break;
    case 17:
        if (*(s16 *)((s32)a0 + 0xA) < -0x402) {
            *(s16 *)((s32)a0 + 0xA) = *(s16 *)((s32)a0 + 0xA) + 1;
        }
        *(u16 *)((s32)a0 + 0xFC) = *(u16 *)((s32)a0 + 0xFC) + 0x10;
        func_80182D4C((s32)a0, func_8004787C(*(s16 *)((s32)a0 + 0xFC)));
        if (*(s16 *)((s32)a0 + 0xFC) >= 0x400) {
            *(u16 *)((s32)a0 + 0x34) = 0x12;
            *(s32 *)((s32)a0 + 0x1C) = 3;
            func_80182D4C((s32)a0, 0x1000);
            func_8002D4C8(0xBC0, 0);
        }
        s5 = 0xD;
        func_8012EC04((s32)a0, 0xD, sp18);
        for (s4 = 0, q = &D_801F61C0[0]; s4 < 6; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0xD];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        s5 = 0xE;
        func_8012EC04((s32)a0, 0xE, sp18);
        for (s4 = 6, q = &D_801F61C0[6]; s4 < 8; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0xE];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        s5 = 0x1;
        func_8012EC04((s32)a0, 0x1, sp18);
        for (s4 = 8, q = &D_801F61C0[8]; s4 < 10; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0x1];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        s5 = 0x2;
        func_8012EC04((s32)a0, 0x2, sp18);
        for (s4 = 10, q = &D_801F61C0[10]; s4 < 11; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0x2];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        s5 = 0x6;
        func_8012EC04((s32)a0, 0x6, sp18);
        for (s4 = 11, q = &D_801F61C0[11]; s4 < 13; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0x6];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        s5 = 0x7;
        func_8012EC04((s32)a0, 0x7, sp18);
        for (s4 = 13, q = &D_801F61C0[13]; s4 < 14; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0x7];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        s5 = 0x8;
        func_8012EC04((s32)a0, 0x8, sp18);
        for (s4 = 14, q = &D_801F61C0[14]; s4 < 16; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0x8];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        break;
    case 18:
        s5 = 0xE;
        func_8012EC04((s32)a0, 0xE, sp18);
        for (s4 = 0, q = &D_801F61C0[0]; s4 < 3; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0xE];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        s5 = 0x1;
        func_8012EC04((s32)a0, 0x1, sp18);
        for (s4 = 3, q = &D_801F61C0[3]; s4 < 5; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0x1];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        s5 = 0x2;
        func_8012EC04((s32)a0, 0x2, sp18);
        for (s4 = 5, q = &D_801F61C0[5]; s4 < 8; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0x2];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        s5 = 0x6;
        func_8012EC04((s32)a0, 0x6, sp18);
        for (s4 = 8, q = &D_801F61C0[8]; s4 < 11; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0x6];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        s5 = 0x7;
        func_8012EC04((s32)a0, 0x7, sp18);
        for (s4 = 11, q = &D_801F61C0[11]; s4 < 13; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0x7];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        s5 = 0x8;
        func_8012EC04((s32)a0, 0x8, sp18);
        for (s4 = 13, q = &D_801F61C0[13]; s4 < 16; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0x8];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        if (*(s32 *)((s32)a0 + 0x1C) < 7) {
            func_80016224(0xFF, 0);
        }
        if ((*(s32 *)((s32)a0 + 0x1C) = *(s32 *)((s32)a0 + 0x1C) - 1) != 0) {
            break;
        }
        *(u16 *)((s32)a0 + 0x34) = 0x13;
        *(s16 *)((s32)a0 + 0xFC) = 0;
        func_8001C214(*(s32 *)((s32)a0 + 0x20), &D_801BF6CC);
        func_8001D0E8(*(s32 *)((s32)a0 + 0x20), 0x280, 0x1E0);
        *(s16 *)(*(s32 *)((s32)a0 + 0x20) + 0x12) = 0x400;
        func_8012A828((s32)a0, &D_801CA678);
        *(s32 *)((s32)a0 + 0x1C) = 0x79;
        break;
    case 19:
        s5 = 0xC;
        func_8012EC04((s32)a0, 0xC, sp18);
        for (s4 = 0, q = &D_801F61C0[0]; s4 < 6; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0xC];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        if (*(s32 *)((s32)a0 + 0x94) < 0x2E) {
            s0 = func_80143C74((s32)a0, 0);
            if (s0 != 0) {
                *(u16 *)(s0 + 0xE) = *(u16 *)(s0 + 0xE) - (rand() & 0x3F);
                *(u16 *)(s0 + 0xA) = (*(u16 *)(s0 + 0xA) - 0x8B) - (rand() & 0x3F);
                *(u16 *)(s0 + 0x6) = *(u16 *)(s0 + 0x6) - 0x9E;
                *(s32 *)(s0 + 0x10) = ((rand() & 0xFF) - 0x80) << 10;
                *(s32 *)(s0 + 0x18) = ((rand() & 0xFF) - 0x80) << 10;
                *(s16 *)(s0 + 0x16) = -((rand() & 3) + 4);
                func_80128EA8(*(s32 *)(s0 + 0x20), s0 + 0xD0, &D_8018DF10);
                func_8012C658(0x3AC, 6, s0);
                func_8012C658(0x3AC, 6, s0);
            }
        }
        if (*(s32 *)((s32)a0 + 0x94) == 0x45 || *(s32 *)((s32)a0 + 0x94) == 0x50) {
            func_8002D4C8(0xBBA, 0);
        }
        if (*(s32 *)((s32)a0 + 0x94) == 0x49 || *(s32 *)((s32)a0 + 0x94) == 0x56) {
            func_8002D4C8(0xBBB, 0);
        }
        if ((*(s32 *)((s32)a0 + 0x1C) = *(s32 *)((s32)a0 + 0x1C) - 1) != 0) {
            break;
        }
        *(u16 *)((s32)a0 + 0x34) = 0x14;
        func_8012A828((s32)a0, &D_801CAA38);
        break;
    case 20:
        s5 = 0xC;
        func_8012EC04((s32)a0, 0xC, sp18);
        for (s4 = 0, q = &D_801F61C0[0]; s4 < 4; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0xC];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        s5 = 0x9;
        func_8012EC04((s32)a0, 0x9, sp18);
        for (s4 = 4, q = &D_801F61C0[4]; s4 < 6; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0x9];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        s5 = 0xA;
        func_8012EC04((s32)a0, 0xA, sp18);
        for (s4 = 6, q = &D_801F61C0[6]; s4 < 7; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0xA];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        s5 = 0xB;
        func_8012EC04((s32)a0, 0xB, sp18);
        for (s4 = 7, q = &D_801F61C0[7]; s4 < 10; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0xB];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        s5 = 0xD;
        func_8012EC04((s32)a0, 0xD, sp18);
        for (s4 = 10, q = &D_801F61C0[10]; s4 < 12; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0xD];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        s5 = 0xE;
        func_8012EC04((s32)a0, 0xE, sp18);
        for (s4 = 12, q = &D_801F61C0[12]; s4 < 13; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0xE];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        s5 = 0xF;
        func_8012EC04((s32)a0, 0xF, sp18);
        for (s4 = 13, q = &D_801F61C0[13]; s4 < 16; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0xF];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        break;
    }

    if (func_80178970((s32)a0) != 0) {
        func_80178D18((s32)a0);
        *(s16 *)((s32)a0 + 0x2) = 3;
    }
}
