/*
 * func_80183814  --  ov_SC07_006 (jr / 21-case jump-table state machine), 5,122 ins.
 * ROUND 2 deliverable, 2026-07-26.  Generated by .run/giants/s21_g21_build.py.
 *
 * STATUS (measured, not claimed):
 *   tools/match_one.py func_80183814 --c <this file> \
 *       --asm-subdir asm/ov_SC07_006/nonmatchings/ov_SC07_006_jr_8017BEBC
 *   ->  MATCH (5122 ins)
 *
 *   Round-1 left 5127 ins / 36 structurally-unmatched / 1201 register-sensitive.
 *   This draft: 5122 ins (= target), 0 structural, 0 register-sensitive,
 *   .frame $sp,248 (= target -0xF8), .mask 0x807f0000 (= ra + $s0..$s6, 8 saves).
 *
 *   match_one is a CANDIDATE gate: it masks jal/HI16/LO16 and never links, so it
 *   is blind to a wrong callee (S87), a duplicated jump table (S81) and a
 *   mis-derived %lo (S84).  .run/giants/s21_g21_reloc_verify.py closes all three
 *   by RESOLVING every relocation (symbol + implicit REL addend) and comparing it
 *   with the address the target names at the same index:
 *       359/359 jal callees OK,  60/60 internal j destinations OK,
 *       406/406 %hi/%lo data addresses OK (incl. the 6 derived-offset sites).
 *   The ONLY unresolved relocation is the switch table itself: this object emits a
 *   local .rodata table where the target uses jtbl_801F4CE4.  That is the 3-step
 *   jr carve chain, owned by banking.  NOT yet whole-binary verified.
 *
 * LEVERS (all drop-one ablated on this final base; every one is load-bearing):
 *   L1  cases 0/3, 2nd call group: reach the three &D_8018E27C-class addresses via
 *       a DISTINCT base symbol (S84 idiom).  Without it gcc CSEs the address
 *       constants across the two call groups that share one basic block, burning
 *       2 callee-saved registers and renaming every register downstream.
 *       drop -> 5132 ins, 26 structural, 773 reg, frame 256, 10 saves.
 *       *** THIS IS A HAND-PLACED DIAL, NOT RECOVERED ORIGINAL SOURCE. ***
 *       Address arithmetic verified: 0x8018E2DC-0x60 == 0x8018E27C etc. (6/6).
 *   L2  the template's own locals (p,q,s0,s1,s4,s5) declared inside the template
 *       block instead of at function scope.   drop -> 6 structural, 754 reg.
 *   L3  KIND==1 template instances carry a preheader compare constant, spelled in
 *       the for-init: `for (s4=S, kk=1, q=&D_801F61C0[S]; ...)` + `p[1] == kk`.
 *       drop -> 5116 ins, 14 structural, 7 saves (target has 8).
 *       *** ALSO A DIAL: it makes 4 of the 35 template instances differ in source
 *       from the other 31.  See the report; the natural spelling is UNKNOWN. ***
 *   L4  the audio ramp's `t`/`idx` declared inside its `if (r >= c)` block.
 *       drop -> 5121 ins, 1 structural, 288 reg.   (This also buys the last
 *       instruction: case 9's delay-slot `li $a0,0x3AC`.)
 *   L5  morph/lerp: `pb = msb;` initialised BEFORE `pa = msa;`.  drop -> 35 reg.
 *   L6  morph/lerp: pointer bumps ordered `md += 4; pb += 4; pa += 4;`.
 *       drop -> 45 reg.
 *   L7  case 19 reads the 0xA field SIGNED: `(*(s16*)(s0+0xA) - 0x8B) - (rand()&0x3F)`.
 *       The unsigned spelling lets combine reassociate to `mem - (r + 0x8B)`.
 *       drop -> 1 structural, 1 reg.  (`(u16)(...)` cast barrier measures identical.)
 *
 * Round-1 levers retained unchanged: the 35x spawn template (one definition,
 * S83b), the running-pointer walk, `rand() % (u32)x` -> divu, the
 * `(s32)((u8*)p + (X+0xC))` cast barrier, the morph pa/pb copy walk (S83e), and
 * NO dead `pad[32]` (S83c -- that block is gcc's spill area).
 */
#include "common.h"

extern s32 func_8004787C(s32 a0);
extern void func_8017FDF8(s32 a0);
extern void func_8017F9AC(s32 a0, void *a1);
extern void func_8017D8A4(s32 a0, void *a1, void *a2, s32 a3, s32 a4);
extern void func_800599B8(void *a0, s32 a1);
extern s32 func_8012C658(s32 a0, s32 a1, s32 a2);
extern void func_8002D4C8(s32 a0, s32 a1);
extern void func_8017F5D4(s32 a0);
extern void func_801805D4(s32 a0, void *a1);
extern void func_8001C214(s32 a0, void *a1);
extern void func_8001D0E8(s32 a0, s32 a1, s32 a2);
extern void func_8012A828(s32 a0, void *a1);
extern void func_80016224(s32 a0, s32 a1);
extern void func_8012EC04(s32 a0, s32 a1, s32 *a2);
extern void func_8012F14C(s32 *a0, s32 a1, s16 *a2);
extern s32 func_8012C51C(s16 *a0, s32 a1);
extern s32 rand(void);
extern s32 func_80178970(s32 a0);
extern void func_80178D18(s32 a0);
extern void func_801802EC(s32 a0);
extern void func_80180924(s32 a0);
extern void func_80180CFC(s32 a0, void *a1);
extern void func_80181148(s32 a0);
extern void func_8018163C(s32 a0);
extern void func_80181924(s32 a0, void *a1);
extern void func_80182268(s32 a0, s32 a1);
extern void func_801823F8(s32 a0);
extern void func_801826E0(s32 a0, s32 a1);
extern void func_801828A4(s32 a0);
extern void func_80182B8C(s32 a0, s32 a1);
extern void func_80181E64(s32 a0, s32 a1);
extern void func_80182000(s32 a0, s32 a1);
extern void func_80182158(s32 a0);
extern void func_80181C74(s32 a0, s32 a1);
extern void func_80182D4C(s32 a0, s32 a1);
extern void func_80128EA8(s32 a0, s32 a1, void *a2);
extern s32 func_80143C74(s32 a0, s32 a1);

extern u8 D_8018E27C;
extern u8 D_8018E288;
extern u8 D_8018E294;
extern u8 D_8018E2A0;
extern u8 D_8018E2DC;
extern u8 D_8018E2E8;
extern u8 D_8018E2F4;
extern u8 D_8018E300;
extern u8 D_8018DFC0;
extern u8 D_8018DFC8;
extern u8 D_8018DFD0;
extern u8 D_8018DFD8;
extern u8 D_8018DFE0;
extern u8 D_8018DFE8;
extern u8 D_8018DFF0;
extern u8 D_8018DFF8;
extern u8 D_8018E000;
extern u8 D_8018E008;
extern u8 D_8018E010;
extern u8 D_8018E018;
extern s32 D_8018E034[];
extern u8 D_8018DF10;
extern s32 D_801BFCB4;
extern s32 D_801BFCBC;
extern s32 D_801BFCC4;
extern u8 D_801BF540;
extern u8 D_801BF588;
extern u8 D_801BFCCC;
extern s32 *D_801BF5CC;
extern u8 D_801BF630;
extern u8 D_801BFCDC;
extern u8 D_801BF658;
extern u8 D_801BFCE4;
extern u8 D_801BF68C;
extern u8 D_801BFCEC;
extern u8 D_801CAA38;
extern u8 D_8018E020;
extern u8 D_8018E028;
extern u8 D_8018E030;
extern u8 D_8018E3A8;
extern u8 D_801BF60C;
extern s32 D_801BFCD4;
extern s16 *D_801C1E14;
extern s16 *D_801C1E18;
extern u8 D_801BF6CC;
extern u8 D_801CA678;
extern s32 *D_801BF604;
extern s32 *D_801BF650;
extern s16 *D_801C1EA0;
extern s16 *D_801C1EA4;
extern s16 *D_801C1EA8;
extern s32 D_801F61C0[];

void func_80183814(void *a0) {
    s32 sp18[8];
    s16 sp38[4];
    s16 sp40[10];
    s32 s3;
    s32 s0;
    s32 s1;
    s32 s4;
    s32 s5;
    s32 c;
    s32 r;
    s32 t;
    s32 idx;
    s32 ok;
    s32 *p;
    s32 *q;

    s0 = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
    s3 = s0 + (func_8004787C(*(s16 *)((s32)a0 + 0xFE)) >> 4);
    *(u16 *)((s32)a0 + 0xFE) = (*(u16 *)((s32)a0 + 0xFE) + 0x300) & 0xFFF;
    if (*(u16 *)((s32)a0 + 0x34) < 0x11) {
        *(s32 *)((s32)a0 + 0x8) =
            (*(s16 *)((s32)a0 + 0x8A) << 16) +
            (func_8004787C(*(s16 *)((s32)a0 + 0x104)) << 7);
        *(u16 *)((s32)a0 + 0x104) = *(u16 *)((s32)a0 + 0x104) + 0x40;
    }

    switch (*(u16 *)((s32)a0 + 0x34)) {
    case 0:
        *(s16 *)((s32)a0 + 0xFC) = *(s16 *)((s32)a0 + 0xFC) + 8;
        func_8017F9AC(s3, a0);
        func_8017D8A4(D_801BFCB4 + 0x3C, &D_8018E27C, &D_8018E27C + 0x30, s3, 1);
        func_8017D8A4(D_801BFCB4 + 0x48, &D_8018E288, &D_8018E288 + 0x30, s3, 1);
        func_8017D8A4(D_801BFCB4 + 0x54, &D_8018E294, &D_8018E294 + 0x30, s3, 1);
        func_8017D8A4(D_801BFCB4 + 0x60, &D_8018E2A0, &D_8018E2A0 + 0x30, s3, 1);
        func_8017FDF8(func_8004787C(*(s16 *)((s32)a0 + 0xFC)));
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            s32 t, idx;
            t = (s16)(c / 455);
            if (t >= 10) {
                t = 9;
            }
            func_800599B8(&D_8018DFC0, D_8018E034[t]);
        }
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            s32 t, idx;
            t = (s16)(c / 455);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 9;
            func_800599B8(&D_8018DFC8, D_8018E034[idx]);
        }
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            s32 t, idx;
            t = (s16)(c / 455);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x12;
            func_800599B8(&D_8018DFD0, D_8018E034[idx]);
        }
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            s32 t, idx;
            t = (s16)(c / 455);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x1B;
            func_800599B8(&D_8018DFD8, D_8018E034[idx]);
        }
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            s32 t, idx;
            t = (s16)(c / 455);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x24;
            func_800599B8(&D_8018DFE0, D_8018E034[idx]);
        }
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            s32 t, idx;
            t = (s16)(c / 455);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x2D;
            func_800599B8(&D_8018DFE8, D_8018E034[idx]);
            ok = 1;
        } else {
            ok = 0;
        }
        if (ok != 0) {
            *(u16 *)((s32)a0 + 0x102) = *(u16 *)((s32)a0 + 0x102) + 0x1C7;
        }
        if (*(s16 *)((s32)a0 + 0xFC) != 0x200) {
            break;
        }
        s1 = 0;
        do {
            s0 = func_8012C658(0x3AC, 0, (s32)a0);
            if (s0 != 0) {
                *(u16 *)(s0 + 0xE) = *(u16 *)(s0 + 0xE) - 0x2D;
                *(u16 *)(s0 + 0xA) = *(u16 *)(s0 + 0xA) - 0x47;
                *(u16 *)(s0 + 0x6) = *(u16 *)(s0 + 0x6) - 5;
            }
            s1 += 1;
        } while (s1 < 0x10);
        func_8002D4C8(0xBBE, 0);
        func_8017F5D4(0x1000);
        func_8017D8A4(D_801BFCB4 + 0x3C, &D_8018E27C, &D_8018E27C + 0x30, 0x1000, 1);
        func_8017D8A4(D_801BFCB4 + 0x48, &D_8018E288, &D_8018E288 + 0x30, 0x1000, 1);
        func_8017D8A4(D_801BFCB4 + 0x54, &D_8018E294, &D_8018E294 + 0x30, 0x1000, 1);
        func_8017D8A4(D_801BFCB4 + 0x60, &D_8018E2A0, &D_8018E2A0 + 0x30, 0x1000, 1);
        *(u16 *)((s32)a0 + 0x34) = 1;
        func_801805D4(s3, a0);
        func_8001C214(*(s32 *)((s32)a0 + 0x20), &D_801BF540);
        func_8001D0E8(*(s32 *)((s32)a0 + 0x20), 0x280, 0x1E0);
        *(s16 *)(*(s32 *)((s32)a0 + 0x20) + 0x12) = 0x400;
        func_8012A828((s32)a0, &D_801BFCBC);
        func_8017D8A4(D_801BFCBC + 0x3C, &D_8018E2DC - 0x60, &D_8018E2DC - 0x30, s3, 1);
        func_8017D8A4(D_801BFCBC + 0x48, &D_8018E2E8 - 0x60, &D_8018E2E8 - 0x30, s3, 1);
        func_8017D8A4(D_801BFCBC + 0x54, &D_8018E2F4 - 0x60, &D_8018E2F4 - 0x30, s3, 1);
        break;
    case 1:
        *(s16 *)((s32)a0 + 0xFC) = *(s16 *)((s32)a0 + 0xFC) + 8;
        func_801805D4(s3, a0);
        func_8017D8A4(D_801BFCBC + 0x3C, &D_8018E27C, &D_8018E27C + 0x30, s3, 1);
        func_8017D8A4(D_801BFCBC + 0x48, &D_8018E288, &D_8018E288 + 0x30, s3, 1);
        func_8017D8A4(D_801BFCBC + 0x54, &D_8018E294, &D_8018E294 + 0x30, s3, 1);
        func_8017FDF8(func_8004787C(*(s16 *)((s32)a0 + 0xFC)));
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            s32 t, idx;
            t = (s16)(c / 455);
            if (t >= 10) {
                t = 9;
            }
            func_800599B8(&D_8018DFC0, D_8018E034[t]);
        }
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            s32 t, idx;
            t = (s16)(c / 455);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 9;
            func_800599B8(&D_8018DFC8, D_8018E034[idx]);
        }
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            s32 t, idx;
            t = (s16)(c / 455);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x12;
            func_800599B8(&D_8018DFD0, D_8018E034[idx]);
        }
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            s32 t, idx;
            t = (s16)(c / 455);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x1B;
            func_800599B8(&D_8018DFD8, D_8018E034[idx]);
        }
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            s32 t, idx;
            t = (s16)(c / 455);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x24;
            func_800599B8(&D_8018DFE0, D_8018E034[idx]);
        }
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            s32 t, idx;
            t = (s16)(c / 455);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x2D;
            func_800599B8(&D_8018DFE8, D_8018E034[idx]);
            ok = 1;
        } else {
            ok = 0;
        }
        if (ok != 0) {
            *(u16 *)((s32)a0 + 0x102) = *(u16 *)((s32)a0 + 0x102) + 0x1C7;
        }
        if (*(s16 *)((s32)a0 + 0xFC) < 0x400) {
            break;
        }
        *(u16 *)((s32)a0 + 0x34) = 2;
        *(s32 *)((s32)a0 + 0x1C) = 0xA;
        func_801802EC(0x1000);
        func_8017D8A4(D_801BFCBC + 0x3C, &D_8018E27C, &D_8018E27C + 0x30, 0x1000, 1);
        func_8017D8A4(D_801BFCBC + 0x48, &D_8018E288, &D_8018E288 + 0x30, 0x1000, 1);
        func_8017D8A4(D_801BFCBC + 0x54, &D_8018E294, &D_8018E294 + 0x30, 0x1000, 1);
        func_8017FDF8(0x1000);
        break;
    case 2:
        if (*(s32 *)((s32)a0 + 0x1C) < 7) {
            func_80016224(0xFF, 0);
        }
        if ((*(s32 *)((s32)a0 + 0x1C) = *(s32 *)((s32)a0 + 0x1C) - 1) != 0) {
            break;
        }
        *(u16 *)((s32)a0 + 0x34) = 3;
        *(s16 *)((s32)a0 + 0xFC) = 0;
        *(u16 *)((s32)a0 + 0x102) = 0x1C7;
        func_8002D4C8(0xBB6, 0);
        break;
    case 3:
        *(s16 *)((s32)a0 + 0xFC) = *(s16 *)((s32)a0 + 0xFC) + 8;
        func_80180CFC(s3, a0);
        func_8017D8A4(D_801BFCBC + 0x84, &D_8018E2DC, &D_8018E2DC + 0x30, s3, 1);
        func_8017D8A4(D_801BFCBC + 0x90, &D_8018E2E8, &D_8018E2E8 + 0x30, s3, 1);
        func_8017D8A4(D_801BFCBC + 0x9C, &D_8018E2F4, &D_8018E2F4 + 0x30, s3, 1);
        func_8017D8A4(D_801BFCBC + 0xA8, &D_8018E300, &D_8018E300 + 0x30, s3, 1);
        func_80181148(func_8004787C(*(s16 *)((s32)a0 + 0xFC)));
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            s32 t, idx;
            t = (s16)(c / 455);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x36;
            func_800599B8(&D_8018DFF0, D_8018E034[idx]);
        }
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            s32 t, idx;
            t = (s16)(c / 455);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x3F;
            func_800599B8(&D_8018DFF8, D_8018E034[idx]);
        }
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            s32 t, idx;
            t = (s16)(c / 455);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x48;
            func_800599B8(&D_8018E000, D_8018E034[idx]);
        }
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            s32 t, idx;
            t = (s16)(c / 455);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x51;
            func_800599B8(&D_8018E008, D_8018E034[idx]);
        }
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            s32 t, idx;
            t = (s16)(c / 455);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x5A;
            func_800599B8(&D_8018E010, D_8018E034[idx]);
        }
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            s32 t, idx;
            t = (s16)(c / 455);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x63;
            func_800599B8(&D_8018E018, D_8018E034[idx]);
            ok = 1;
        } else {
            ok = 0;
        }
        if (ok != 0) {
            *(u16 *)((s32)a0 + 0x102) = *(u16 *)((s32)a0 + 0x102) + 0x1C7;
        }
        if (*(s16 *)((s32)a0 + 0xFC) < 0x200) {
            break;
        }
        s1 = 0;
        do {
            s0 = func_8012C658(0x3AC, 0, (s32)a0);
            if (s0 != 0) {
                *(u16 *)(s0 + 0xE) = *(u16 *)(s0 + 0xE) + 0x2D;
                *(u16 *)(s0 + 0xA) = *(u16 *)(s0 + 0xA) - 0x47;
                *(u16 *)(s0 + 0x6) = *(u16 *)(s0 + 0x6) - 5;
            }
            s1 += 1;
        } while (s1 < 0x10);
        func_8002D4C8(0xBBE, 0);
        func_80180924(0x1000);
        func_8017D8A4(D_801BFCBC + 0x84, &D_8018E2DC, &D_8018E2DC + 0x30, 0x1000, 1);
        func_8017D8A4(D_801BFCBC + 0x90, &D_8018E2E8, &D_8018E2E8 + 0x30, 0x1000, 1);
        func_8017D8A4(D_801BFCBC + 0x9C, &D_8018E2F4, &D_8018E2F4 + 0x30, 0x1000, 1);
        func_8017D8A4(D_801BFCBC + 0xA8, &D_8018E300, &D_8018E300 + 0x30, 0x1000, 1);
        *(u16 *)((s32)a0 + 0x34) = 4;
        func_80181924(s3, a0);
        func_8001C214(*(s32 *)((s32)a0 + 0x20), &D_801BF588);
        func_8001D0E8(*(s32 *)((s32)a0 + 0x20), 0x280, 0x1E0);
        *(s16 *)(*(s32 *)((s32)a0 + 0x20) + 0x12) = 0x400;
        func_8012A828((s32)a0, &D_801BFCC4);
        func_8017D8A4(D_801BFCC4 + 0x84, &D_8018E27C + 0x60, &D_8018E27C + 0x90, s3, 1);
        func_8017D8A4(D_801BFCC4 + 0x90, &D_8018E288 + 0x60, &D_8018E288 + 0x90, s3, 1);
        func_8017D8A4(D_801BFCC4 + 0x9C, &D_8018E294 + 0x60, &D_8018E294 + 0x90, s3, 1);
        break;
    case 4:
        *(s16 *)((s32)a0 + 0xFC) = *(s16 *)((s32)a0 + 0xFC) + 8;
        func_80181924(s3, a0);
        func_8017D8A4(D_801BFCC4 + 0x84, &D_8018E2DC, &D_8018E2DC + 0x30, s3, 1);
        func_8017D8A4(D_801BFCC4 + 0x90, &D_8018E2E8, &D_8018E2E8 + 0x30, s3, 1);
        func_8017D8A4(D_801BFCC4 + 0x9C, &D_8018E2F4, &D_8018E2F4 + 0x30, s3, 1);
        func_80181148(func_8004787C(*(s16 *)((s32)a0 + 0xFC)));
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            s32 t, idx;
            t = (s16)(c / 455);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x36;
            func_800599B8(&D_8018DFF0, D_8018E034[idx]);
        }
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            s32 t, idx;
            t = (s16)(c / 455);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x3F;
            func_800599B8(&D_8018DFF8, D_8018E034[idx]);
        }
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            s32 t, idx;
            t = (s16)(c / 455);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x48;
            func_800599B8(&D_8018E000, D_8018E034[idx]);
        }
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            s32 t, idx;
            t = (s16)(c / 455);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x51;
            func_800599B8(&D_8018E008, D_8018E034[idx]);
        }
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            s32 t, idx;
            t = (s16)(c / 455);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x5A;
            func_800599B8(&D_8018E010, D_8018E034[idx]);
        }
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            s32 t, idx;
            t = (s16)(c / 455);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x63;
            func_800599B8(&D_8018E018, D_8018E034[idx]);
            ok = 1;
        } else {
            ok = 0;
        }
        if (ok != 0) {
            *(u16 *)((s32)a0 + 0x102) = *(u16 *)((s32)a0 + 0x102) + 0x199;
        }
        if (*(s16 *)((s32)a0 + 0xFC) < 0x400) {
            break;
        }
        *(u16 *)((s32)a0 + 0x34) = 5;
        *(s32 *)((s32)a0 + 0x1C) = 0xA;
        func_8018163C(0x1000);
        func_8017D8A4(D_801BFCC4 + 0x84, &D_8018E2DC, &D_8018E2DC + 0x30, 0x1000, 1);
        func_8017D8A4(D_801BFCC4 + 0x90, &D_8018E2E8, &D_8018E2E8 + 0x30, 0x1000, 1);
        func_8017D8A4(D_801BFCC4 + 0x9C, &D_8018E2F4, &D_8018E2F4 + 0x30, 0x1000, 1);
        func_80181148(0x1000);
        break;
    case 5:
        if (*(s32 *)((s32)a0 + 0x1C) < 7) {
            func_80016224(0xFF, 0);
        }
        if ((*(s32 *)((s32)a0 + 0x1C) = *(s32 *)((s32)a0 + 0x1C) - 1) != 0) {
            break;
        }
        *(u16 *)((s32)a0 + 0x34) = 6;
        *(s16 *)((s32)a0 + 0xFC) = 0;
        func_8001C214(*(s32 *)((s32)a0 + 0x20), &D_801BF5CC);
        func_8001D0E8(*(s32 *)((s32)a0 + 0x20), 0x280, 0x1E0);
        *(s16 *)(*(s32 *)((s32)a0 + 0x20) + 0x12) = 0x400;
        func_8012A828((s32)a0, &D_801BFCCC);
        func_8012C658(0x3AC, 1, (s32)a0);
        *(u16 *)((s32)a0 + 0x102) = 0x1C7;
        func_8002D4C8(0xBB9, 0);
        func_8002D4C8(0xC6F, 0);
        break;
    case 6:
        *(s16 *)((s32)a0 + 0xFC) = *(s16 *)((s32)a0 + 0xFC) + 8;
        {
            s32 *mp;
            s16 *md;
            s16 *msa;
            s16 *msb;
            s32 mn;
            s16 *pa;
            s16 *pb;

            mp = D_801BF604;
            msb = D_801C1EA0;
            msa = D_801C1EA4;
            if (mp[1] == 1) {
                md = (s16 *)mp[3];
            } else {
                md = (s16 *)((u8 *)mp + ((((u32)mp[3] >> 2) << 2) + 0xC));
            }
            mn = mp[4];
            pb = msb;
            pa = msa;
            while (mn != 0) {
                md[0] = pb[0] + (((pa[0] - pb[0]) * s3) >> 12);
                md[1] = pb[1] + (((pa[1] - pb[1]) * s3) >> 12);
                md[2] = pb[2] + (((pa[2] - pb[2]) * s3) >> 12);
                md += 4;
                pb += 4;
                pa += 4;
                mn--;
            }
        }
        func_80181C74((s32)a0, s3);
        if (*(s16 *)((s32)a0 + 0xFC) < 0x400) {
            break;
        }
        *(u16 *)((s32)a0 + 0x34) = 7;
        *(s32 *)((s32)a0 + 0x1C) = 0xA;
        t = 0x1000;
        {
            s32 *mp;
            s16 *md;
            s16 *msa;
            s16 *msb;
            s32 mn;
            s16 *pa;
            s16 *pb;

            mp = D_801BF604;
            msb = D_801C1EA0;
            msa = D_801C1EA4;
            if (mp[1] == 1) {
                md = (s16 *)mp[3];
            } else {
                md = (s16 *)((u8 *)mp + ((((u32)mp[3] >> 2) << 2) + 0xC));
            }
            mn = mp[4];
            pb = msb;
            pa = msa;
            while (mn != 0) {
                md[0] = pb[0] + (((pa[0] - pb[0]) * t) >> 12);
                md[1] = pb[1] + (((pa[1] - pb[1]) * t) >> 12);
                md[2] = pb[2] + (((pa[2] - pb[2]) * t) >> 12);
                md += 4;
                pb += 4;
                pa += 4;
                mn--;
            }
        }
        func_80181C74((s32)a0, 0x1000);
        break;
    case 7:
        if (*(s32 *)((s32)a0 + 0x1C) < 7) {
            func_80016224(0xFF, 0);
        }
        if ((*(s32 *)((s32)a0 + 0x1C) = *(s32 *)((s32)a0 + 0x1C) - 1) != 0) {
            break;
        }
        *(u16 *)((s32)a0 + 0x34) = 8;
        *(s16 *)((s32)a0 + 0xFC) = 0;
        func_8002D4C8(0xBBC, 0);
        break;
    case 8:
        *(s16 *)((s32)a0 + 0xFC) = *(s16 *)((s32)a0 + 0xFC) + 8;
        func_80181E64(func_8004787C(*(s16 *)((s32)a0 + 0xFC)), (s32)a0);
        func_80182000((s32)a0, func_8004787C(*(s16 *)((s32)a0 + 0xFC)));
        func_80182158(func_8004787C(*(s16 *)((s32)a0 + 0xFC)));
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            s32 t, idx;
            t = (s16)(c / 409);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x7E;
            func_800599B8(&D_8018E030, D_8018E034[idx]);
        }
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            s32 t, idx;
            t = (s16)(c / 409);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x6C;
            func_800599B8(&D_8018E020, D_8018E034[idx]);
        }
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            s32 t, idx;
            t = (s16)(c / 409);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x75;
            func_800599B8(&D_8018E028, D_8018E034[idx]);
            ok = 1;
        } else {
            ok = 0;
        }
        if (ok != 0) {
            *(u16 *)((s32)a0 + 0x102) = *(u16 *)((s32)a0 + 0x102) + 0x199;
        }
        if (*(s16 *)((s32)a0 + 0xFC) < 0x200) {
            break;
        }
        func_8001C214(*(s32 *)((s32)a0 + 0x20), &D_801BF60C);
        func_8001D0E8(*(s32 *)((s32)a0 + 0x20), 0x280, 0x1E0);
        *(s16 *)(*(s32 *)((s32)a0 + 0x20) + 0x12) = 0x400;
        func_8012A828((s32)a0, &D_801BFCD4);
        func_8012C658(0x3AC, 2, (s32)a0);
        func_8012C658(0x3AC, 3, (s32)a0);
        *(u16 *)((s32)a0 + 0x34) = 9;
        func_80181E64(func_8004787C(*(s16 *)((s32)a0 + 0xFC)), (s32)a0);
        func_8017D8A4(D_801BFCD4, &D_8018E3A8, &D_8018E3A8 + 0xB4,
                      func_8004787C(*(s16 *)((s32)a0 + 0xFC)), 1);
        break;
    case 9:
        *(s16 *)((s32)a0 + 0xFC) = *(s16 *)((s32)a0 + 0xFC) + 8;
        func_80181E64(func_8004787C(*(s16 *)((s32)a0 + 0xFC)), (s32)a0);
        func_8017D8A4(D_801BFCD4, &D_8018E3A8, &D_8018E3A8 + 0xB4,
                      func_8004787C(*(s16 *)((s32)a0 + 0xFC)), 1);
        func_80182158(func_8004787C(*(s16 *)((s32)a0 + 0xFC)));
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            s32 t, idx;
            t = (s16)(c / 409);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x7E;
            func_800599B8(&D_8018E030, D_8018E034[idx]);
        }
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            s32 t, idx;
            t = (s16)(c / 409);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x6C;
            func_800599B8(&D_8018E020, D_8018E034[idx]);
        }
        r = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        c = (s16) * (u16 *)((s32)a0 + 0x102);
        if (r >= c) {
            s32 t, idx;
            t = (s16)(c / 409);
            if (t >= 10) {
                t = 9;
            }
            idx = t + 0x75;
            func_800599B8(&D_8018E028, D_8018E034[idx]);
            ok = 1;
        } else {
            ok = 0;
        }
        if (ok != 0) {
            *(u16 *)((s32)a0 + 0x102) = *(u16 *)((s32)a0 + 0x102) + 0x199;
        }
        if (*(s16 *)((s32)a0 + 0xFC) >= 0x400) {
            *(u16 *)((s32)a0 + 0x34) = 0xA;
            *(s32 *)((s32)a0 + 0x1C) = 0xA;
            t = 0x1000;
        {
            s32 *mp;
            s16 *md;
            s16 *msa;
            s16 *msb;
            s32 mn;
            s16 *pa;
            s16 *pb;

            mp = D_801BF5CC;
            msb = D_801C1E14;
            msa = D_801C1E18;
            if (mp[1] == 1) {
                md = (s16 *)mp[3];
            } else {
                md = (s16 *)((u8 *)mp + ((((u32)mp[3] >> 2) << 2) + 0xC));
            }
            mn = mp[4];
            pb = msb;
            pa = msa;
            while (mn != 0) {
                md[0] = pb[0] + (((pa[0] - pb[0]) * t) >> 12);
                md[1] = pb[1] + (((pa[1] - pb[1]) * t) >> 12);
                md[2] = pb[2] + (((pa[2] - pb[2]) * t) >> 12);
                md += 4;
                pb += 4;
                pa += 4;
                mn--;
            }
        }
            func_8017D8A4(D_801BFCD4, &D_8018E3A8, &D_8018E3A8 + 0xB4, 0x1000, 1);
            func_80182158(0x1000);
        }
        s0 = func_8012C658(0x3AC, 6, (s32)a0);
        if (s0 != 0) {
            *(u16 *)(s0 + 0x6) = *(u16 *)(s0 + 0x6) - 0x20;
            *(u16 *)(s0 + 0xA) = *(u16 *)(s0 + 0xA) - 0x140;
            *(u16 *)(s0 + 0xE) = *(u16 *)(s0 + 0xE) - 0x40;
            *(s16 *)(s0 + 0x12) = (rand() & 7) - 4;
            *(s16 *)(s0 + 0x16) = 0;
            *(s16 *)(s0 + 0x1A) = -((rand() & 7) + 0xA);
        }
        s0 = func_8012C658(0x3AC, 6, (s32)a0);
        if (s0 == 0) {
            break;
        }
        *(u16 *)(s0 + 0x6) = *(u16 *)(s0 + 0x6) - 0x20;
        *(u16 *)(s0 + 0xA) = *(u16 *)(s0 + 0xA) - 0x140;
        *(u16 *)(s0 + 0xE) = *(u16 *)(s0 + 0xE) + 0x40;
        *(s16 *)(s0 + 0x12) = (rand() & 7) - 4;
        *(s16 *)(s0 + 0x16) = 0;
        *(s16 *)(s0 + 0x1A) = (rand() & 7) + 0xA;
        break;
    case 10:
        if (*(s32 *)((s32)a0 + 0x1C) < 7) {
            func_80016224(0xFF, 0);
        }
        if ((*(s32 *)((s32)a0 + 0x1C) = *(s32 *)((s32)a0 + 0x1C) - 1) != 0) {
            break;
        }
        *(u16 *)((s32)a0 + 0x34) = 0xB;
        *(s16 *)((s32)a0 + 0xFC) = 0;
        func_8001C214(*(s32 *)((s32)a0 + 0x20), &D_801BF630);
        func_8001D0E8(*(s32 *)((s32)a0 + 0x20), 0x280, 0x1E0);
        *(s16 *)(*(s32 *)((s32)a0 + 0x20) + 0x12) = 0x400;
        func_8012A828((s32)a0, &D_801BFCDC);
        func_8002D4C8(0xBBF, 0);
        break;
    case 11:
        *(s16 *)((s32)a0 + 0xFC) = *(s16 *)((s32)a0 + 0xFC) + 0x10;
        t = func_8004787C(*(s16 *)((s32)a0 + 0xFC));
        {
            s32 *mp;
            s16 *md;
            s16 *msa;
            s16 *msb;
            s32 mn;
            s16 *pa;
            s16 *pb;

            mp = D_801BF650;
            msb = D_801C1EA4;
            msa = D_801C1EA8;
            if (mp[1] == 1) {
                md = (s16 *)mp[3];
            } else {
                md = (s16 *)((u8 *)mp + ((((u32)mp[3] >> 2) << 2) + 0xC));
            }
            mn = mp[4];
            pb = msb;
            pa = msa;
            while (mn != 0) {
                md[0] = pb[0] + (((pa[0] - pb[0]) * t) >> 12);
                md[1] = pb[1] + (((pa[1] - pb[1]) * t) >> 12);
                md[2] = pb[2] + (((pa[2] - pb[2]) * t) >> 12);
                md += 4;
                pb += 4;
                pa += 4;
                mn--;
            }
        }
        func_80182268((s32)a0, func_8004787C(*(s16 *)((s32)a0 + 0xFC)));
        if (*(s16 *)((s32)a0 + 0xFC) >= 0x400) {
            *(u16 *)((s32)a0 + 0x34) = 0xC;
            *(s32 *)((s32)a0 + 0x1C) = 0x1E;
            t = 0x1000;
        {
            s32 *mp;
            s16 *md;
            s16 *msa;
            s16 *msb;
            s32 mn;
            s16 *pa;
            s16 *pb;

            mp = D_801BF650;
            msb = D_801C1EA4;
            msa = D_801C1EA8;
            if (mp[1] == 1) {
                md = (s16 *)mp[3];
            } else {
                md = (s16 *)((u8 *)mp + ((((u32)mp[3] >> 2) << 2) + 0xC));
            }
            mn = mp[4];
            pb = msb;
            pa = msa;
            while (mn != 0) {
                md[0] = pb[0] + (((pa[0] - pb[0]) * t) >> 12);
                md[1] = pb[1] + (((pa[1] - pb[1]) * t) >> 12);
                md[2] = pb[2] + (((pa[2] - pb[2]) * t) >> 12);
                md += 4;
                pb += 4;
                pa += 4;
                mn--;
            }
        }
            func_80182268((s32)a0, 0x1000);
        }
        {
            s32 *p, *q;
            s32 s0, s1, s4, s5;
        s5 = 0x8;
        func_8012EC04((s32)a0, 0x8, sp18);
        for (s4 = 0, q = &D_801F61C0[0]; s4 < 8; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0x8];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        }
        break;
    case 12:
        if (*(s32 *)((s32)a0 + 0x1C) < 7) {
            func_80016224(0xFF, 0);
        }
        *(s32 *)((s32)a0 + 0x1C) = *(s32 *)((s32)a0 + 0x1C) - 1;
        {
            s32 *p, *q;
            s32 s0, s1, s4, s5;
        s5 = 0x8;
        func_8012EC04((s32)a0, 0x8, sp18);
        for (s4 = 0, q = &D_801F61C0[0]; s4 < 8; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0x8];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        }
        if (*(s32 *)((s32)a0 + 0x1C) != 0) {
            break;
        }
        *(u16 *)((s32)a0 + 0x34) = 0xD;
        *(s16 *)((s32)a0 + 0xFC) = 0;
        func_8001C214(*(s32 *)((s32)a0 + 0x20), &D_801BF658);
        func_8001D0E8(*(s32 *)((s32)a0 + 0x20), 0x280, 0x1E0);
        *(s16 *)(*(s32 *)((s32)a0 + 0x20) + 0x12) = 0x400;
        func_8012A828((s32)a0, &D_801BFCE4);
        func_8002D4C8(0xBBD, 0);
        break;
    case 13:
        *(s16 *)((s32)a0 + 0xFC) = *(s16 *)((s32)a0 + 0xFC) + 0x60;
        func_801823F8(func_8004787C(*(s16 *)((s32)a0 + 0xFC)));
        func_801826E0((s32)a0, func_8004787C(*(s16 *)((s32)a0 + 0xFC)));
        if (*(s16 *)((s32)a0 + 0xFC) >= 0x400) {
            *(u16 *)((s32)a0 + 0x34) = 0xE;
            *(s32 *)((s32)a0 + 0x1C) = 0x1E;
            func_801823F8(0x1000);
            func_801826E0((s32)a0, 0x1000);
        }
        {
            s32 *p, *q;
            s32 s0, s1, s4, s5;
            s32 kk;
        s5 = 0x1;
        func_8012EC04((s32)a0, 0x1, sp18);
        for (s4 = 0, kk = 1, q = &D_801F61C0[0]; s4 < 4; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0x1];
                if (p[1] == kk) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        }
        {
            s32 *p, *q;
            s32 s0, s1, s4, s5;
        s5 = 0x2;
        func_8012EC04((s32)a0, 0x2, sp18);
        for (s4 = 4, q = &D_801F61C0[4]; s4 < 8; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0x2];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        }
        {
            s32 *p, *q;
            s32 s0, s1, s4, s5;
        s5 = 0xB;
        func_8012EC04((s32)a0, 0xB, sp18);
        for (s4 = 8, q = &D_801F61C0[8]; s4 < 12; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0xB];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        }
        break;
    case 14:
        {
            s32 *p, *q;
            s32 s0, s1, s4, s5;
            s32 kk;
        s5 = 0x1;
        func_8012EC04((s32)a0, 0x1, sp18);
        for (s4 = 0, kk = 1, q = &D_801F61C0[0]; s4 < 4; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0x1];
                if (p[1] == kk) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        }
        {
            s32 *p, *q;
            s32 s0, s1, s4, s5;
        s5 = 0x2;
        func_8012EC04((s32)a0, 0x2, sp18);
        for (s4 = 4, q = &D_801F61C0[4]; s4 < 8; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0x2];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        }
        {
            s32 *p, *q;
            s32 s0, s1, s4, s5;
        s5 = 0xB;
        func_8012EC04((s32)a0, 0xB, sp18);
        for (s4 = 8, q = &D_801F61C0[8]; s4 < 12; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0xB];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        }
        if (*(s32 *)((s32)a0 + 0x1C) < 7) {
            func_80016224(0xFF, 0);
        }
        if ((*(s32 *)((s32)a0 + 0x1C) = *(s32 *)((s32)a0 + 0x1C) - 1) != 0) {
            break;
        }
        *(u16 *)((s32)a0 + 0x34) = 0xF;
        *(s16 *)((s32)a0 + 0xFC) = 0;
        func_8001C214(*(s32 *)((s32)a0 + 0x20), &D_801BF68C);
        func_8001D0E8(*(s32 *)((s32)a0 + 0x20), 0x280, 0x1E0);
        *(s16 *)(*(s32 *)((s32)a0 + 0x20) + 0x12) = 0x400;
        func_8012A828((s32)a0, &D_801BFCEC);
        func_8002D4C8(0xBBD, 0);
        break;
    case 15:
        *(s16 *)((s32)a0 + 0xFC) = *(s16 *)((s32)a0 + 0xFC) + 0x60;
        func_801828A4(func_8004787C(*(s16 *)((s32)a0 + 0xFC)));
        func_80182B8C((s32)a0, func_8004787C(*(s16 *)((s32)a0 + 0xFC)));
        if (*(s16 *)((s32)a0 + 0xFC) >= 0x400) {
            *(u16 *)((s32)a0 + 0x34) = 0x10;
            *(s32 *)((s32)a0 + 0x1C) = 0x1E;
            func_801828A4(0x1000);
            func_80182B8C((s32)a0, 0x1000);
        }
        {
            s32 *p, *q;
            s32 s0, s1, s4, s5;
        s5 = 0x6;
        func_8012EC04((s32)a0, 0x6, sp18);
        for (s4 = 0, q = &D_801F61C0[0]; s4 < 4; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0x6];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        }
        {
            s32 *p, *q;
            s32 s0, s1, s4, s5;
        s5 = 0x7;
        func_8012EC04((s32)a0, 0x7, sp18);
        for (s4 = 4, q = &D_801F61C0[4]; s4 < 8; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0x7];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        }
        {
            s32 *p, *q;
            s32 s0, s1, s4, s5;
        s5 = 0x8;
        func_8012EC04((s32)a0, 0x8, sp18);
        for (s4 = 8, q = &D_801F61C0[8]; s4 < 12; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0x8];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        }
        break;
    case 16:
        {
            s32 *p, *q;
            s32 s0, s1, s4, s5;
        s5 = 0x6;
        func_8012EC04((s32)a0, 0x6, sp18);
        for (s4 = 0, q = &D_801F61C0[0]; s4 < 4; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0x6];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        }
        {
            s32 *p, *q;
            s32 s0, s1, s4, s5;
        s5 = 0x7;
        func_8012EC04((s32)a0, 0x7, sp18);
        for (s4 = 4, q = &D_801F61C0[4]; s4 < 8; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0x7];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        }
        {
            s32 *p, *q;
            s32 s0, s1, s4, s5;
        s5 = 0x8;
        func_8012EC04((s32)a0, 0x8, sp18);
        for (s4 = 8, q = &D_801F61C0[8]; s4 < 12; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0x8];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        }
        if (*(s32 *)((s32)a0 + 0x1C) < 7) {
            func_80016224(0xFF, 0);
        }
        if ((*(s32 *)((s32)a0 + 0x1C) = *(s32 *)((s32)a0 + 0x1C) - 1) != 0) {
            break;
        }
        *(u16 *)((s32)a0 + 0x34) = 0x11;
        *(s16 *)((s32)a0 + 0xFC) = 0;
        break;
    case 17:
        if (*(s16 *)((s32)a0 + 0xA) < -0x402) {
            *(s16 *)((s32)a0 + 0xA) = *(s16 *)((s32)a0 + 0xA) + 1;
        }
        *(u16 *)((s32)a0 + 0xFC) = *(u16 *)((s32)a0 + 0xFC) + 0x10;
        func_80182D4C((s32)a0, func_8004787C(*(s16 *)((s32)a0 + 0xFC)));
        if (*(s16 *)((s32)a0 + 0xFC) >= 0x400) {
            *(u16 *)((s32)a0 + 0x34) = 0x12;
            *(s32 *)((s32)a0 + 0x1C) = 3;
            func_80182D4C((s32)a0, 0x1000);
            func_8002D4C8(0xBC0, 0);
        }
        {
            s32 *p, *q;
            s32 s0, s1, s4, s5;
        s5 = 0xD;
        func_8012EC04((s32)a0, 0xD, sp18);
        for (s4 = 0, q = &D_801F61C0[0]; s4 < 6; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0xD];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        }
        {
            s32 *p, *q;
            s32 s0, s1, s4, s5;
        s5 = 0xE;
        func_8012EC04((s32)a0, 0xE, sp18);
        for (s4 = 6, q = &D_801F61C0[6]; s4 < 8; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0xE];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        }
        {
            s32 *p, *q;
            s32 s0, s1, s4, s5;
            s32 kk;
        s5 = 0x1;
        func_8012EC04((s32)a0, 0x1, sp18);
        for (s4 = 8, kk = 1, q = &D_801F61C0[8]; s4 < 10; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0x1];
                if (p[1] == kk) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        }
        {
            s32 *p, *q;
            s32 s0, s1, s4, s5;
        s5 = 0x2;
        func_8012EC04((s32)a0, 0x2, sp18);
        for (s4 = 10, q = &D_801F61C0[10]; s4 < 11; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0x2];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        }
        {
            s32 *p, *q;
            s32 s0, s1, s4, s5;
        s5 = 0x6;
        func_8012EC04((s32)a0, 0x6, sp18);
        for (s4 = 11, q = &D_801F61C0[11]; s4 < 13; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0x6];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        }
        {
            s32 *p, *q;
            s32 s0, s1, s4, s5;
        s5 = 0x7;
        func_8012EC04((s32)a0, 0x7, sp18);
        for (s4 = 13, q = &D_801F61C0[13]; s4 < 14; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0x7];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        }
        {
            s32 *p, *q;
            s32 s0, s1, s4, s5;
        s5 = 0x8;
        func_8012EC04((s32)a0, 0x8, sp18);
        for (s4 = 14, q = &D_801F61C0[14]; s4 < 16; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0x8];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        }
        break;
    case 18:
        {
            s32 *p, *q;
            s32 s0, s1, s4, s5;
        s5 = 0xE;
        func_8012EC04((s32)a0, 0xE, sp18);
        for (s4 = 0, q = &D_801F61C0[0]; s4 < 3; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0xE];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        }
        {
            s32 *p, *q;
            s32 s0, s1, s4, s5;
            s32 kk;
        s5 = 0x1;
        func_8012EC04((s32)a0, 0x1, sp18);
        for (s4 = 3, kk = 1, q = &D_801F61C0[3]; s4 < 5; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0x1];
                if (p[1] == kk) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        }
        {
            s32 *p, *q;
            s32 s0, s1, s4, s5;
        s5 = 0x2;
        func_8012EC04((s32)a0, 0x2, sp18);
        for (s4 = 5, q = &D_801F61C0[5]; s4 < 8; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0x2];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        }
        {
            s32 *p, *q;
            s32 s0, s1, s4, s5;
        s5 = 0x6;
        func_8012EC04((s32)a0, 0x6, sp18);
        for (s4 = 8, q = &D_801F61C0[8]; s4 < 11; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0x6];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        }
        {
            s32 *p, *q;
            s32 s0, s1, s4, s5;
        s5 = 0x7;
        func_8012EC04((s32)a0, 0x7, sp18);
        for (s4 = 11, q = &D_801F61C0[11]; s4 < 13; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0x7];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        }
        {
            s32 *p, *q;
            s32 s0, s1, s4, s5;
        s5 = 0x8;
        func_8012EC04((s32)a0, 0x8, sp18);
        for (s4 = 13, q = &D_801F61C0[13]; s4 < 16; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0x8];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        }
        if (*(s32 *)((s32)a0 + 0x1C) < 7) {
            func_80016224(0xFF, 0);
        }
        if ((*(s32 *)((s32)a0 + 0x1C) = *(s32 *)((s32)a0 + 0x1C) - 1) != 0) {
            break;
        }
        *(u16 *)((s32)a0 + 0x34) = 0x13;
        *(s16 *)((s32)a0 + 0xFC) = 0;
        func_8001C214(*(s32 *)((s32)a0 + 0x20), &D_801BF6CC);
        func_8001D0E8(*(s32 *)((s32)a0 + 0x20), 0x280, 0x1E0);
        *(s16 *)(*(s32 *)((s32)a0 + 0x20) + 0x12) = 0x400;
        func_8012A828((s32)a0, &D_801CA678);
        *(s32 *)((s32)a0 + 0x1C) = 0x79;
        break;
    case 19:
        {
            s32 *p, *q;
            s32 s0, s1, s4, s5;
        s5 = 0xC;
        func_8012EC04((s32)a0, 0xC, sp18);
        for (s4 = 0, q = &D_801F61C0[0]; s4 < 6; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0xC];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        }
        if (*(s32 *)((s32)a0 + 0x94) < 0x2E) {
            s0 = func_80143C74((s32)a0, 0);
            if (s0 != 0) {
                *(u16 *)(s0 + 0xE) = *(u16 *)(s0 + 0xE) - (rand() & 0x3F);
                *(u16 *)(s0 + 0xA) = (*(s16 *)(s0 + 0xA) - 0x8B) - (rand() & 0x3F);
                *(u16 *)(s0 + 0x6) = *(u16 *)(s0 + 0x6) - 0x9E;
                *(s32 *)(s0 + 0x10) = ((rand() & 0xFF) - 0x80) << 10;
                *(s32 *)(s0 + 0x18) = ((rand() & 0xFF) - 0x80) << 10;
                *(s16 *)(s0 + 0x16) = -((rand() & 3) + 4);
                func_80128EA8(*(s32 *)(s0 + 0x20), s0 + 0xD0, &D_8018DF10);
                func_8012C658(0x3AC, 6, s0);
                func_8012C658(0x3AC, 6, s0);
            }
        }
        if (*(s32 *)((s32)a0 + 0x94) == 0x45 || *(s32 *)((s32)a0 + 0x94) == 0x50) {
            func_8002D4C8(0xBBA, 0);
        }
        if (*(s32 *)((s32)a0 + 0x94) == 0x49 || *(s32 *)((s32)a0 + 0x94) == 0x56) {
            func_8002D4C8(0xBBB, 0);
        }
        if ((*(s32 *)((s32)a0 + 0x1C) = *(s32 *)((s32)a0 + 0x1C) - 1) != 0) {
            break;
        }
        *(u16 *)((s32)a0 + 0x34) = 0x14;
        func_8012A828((s32)a0, &D_801CAA38);
        break;
    case 20:
        {
            s32 *p, *q;
            s32 s0, s1, s4, s5;
        s5 = 0xC;
        func_8012EC04((s32)a0, 0xC, sp18);
        for (s4 = 0, q = &D_801F61C0[0]; s4 < 4; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0xC];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        }
        {
            s32 *p, *q;
            s32 s0, s1, s4, s5;
        s5 = 0x9;
        func_8012EC04((s32)a0, 0x9, sp18);
        for (s4 = 4, q = &D_801F61C0[4]; s4 < 6; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0x9];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        }
        {
            s32 *p, *q;
            s32 s0, s1, s4, s5;
        s5 = 0xA;
        func_8012EC04((s32)a0, 0xA, sp18);
        for (s4 = 6, q = &D_801F61C0[6]; s4 < 7; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0xA];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        }
        {
            s32 *p, *q;
            s32 s0, s1, s4, s5;
        s5 = 0xB;
        func_8012EC04((s32)a0, 0xB, sp18);
        for (s4 = 7, q = &D_801F61C0[7]; s4 < 10; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0xB];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        }
        {
            s32 *p, *q;
            s32 s0, s1, s4, s5;
        s5 = 0xD;
        func_8012EC04((s32)a0, 0xD, sp18);
        for (s4 = 10, q = &D_801F61C0[10]; s4 < 12; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0xD];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        }
        {
            s32 *p, *q;
            s32 s0, s1, s4, s5;
        s5 = 0xE;
        func_8012EC04((s32)a0, 0xE, sp18);
        for (s4 = 12, q = &D_801F61C0[12]; s4 < 13; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0xE];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        }
        {
            s32 *p, *q;
            s32 s0, s1, s4, s5;
        s5 = 0xF;
        func_8012EC04((s32)a0, 0xF, sp18);
        for (s4 = 13, q = &D_801F61C0[13]; s4 < 16; s4++, q++) {
            if (*q % 80 == 0) {
                p = ((s32 **)(*(s32 *)(*(s32 *)((s32)a0 + 0x20) + 0x24)))[0xF];
                if (p[1] == 1) {
                    s1 = p[3];
                } else {
                    s1 = (s32)((u8 *)p + ((((u32)p[3] >> 2) << 2) + 0xC));
                }
                s0 = p[4] - 1;
                s1 = s1 + (rand() % (u32)s0) * 8;
                func_8012F14C(sp18, s1, sp38);
                sp40[3] = 0x3C5;
                sp40[7] = s5;
                sp40[5] = 0;
                sp40[4] = 0;
                *(s32 *)&sp40[8] = s1;
                sp40[6] = 0x7FFF;
                sp40[0] = sp38[0];
                sp40[1] = sp38[1];
                sp40[2] = sp38[2];
                func_8012C51C(sp40, (s32)a0);
            }
        }
        }
        break;
    }

    if (func_80178970((s32)a0) != 0) {
        func_80178D18((s32)a0);
        *(s16 *)((s32)a0 + 0x2) = 3;
    }
}
