#!/usr/bin/env python3
"""Extract inline-defined NAMED struct/union types from an overlay .c into a shared header.

Phase 15 / T6 struct follow-up (cookbook §14c). The harvest agents defined engine struct types
INLINE in each function's draft. Those bodies then can't be propagated as engine_core.h macros (two
macros defining the same-named type redefine it; a type used in a shared callee's extern conflicts).
Scoped finding: the 34 named struct/union types in ov_SC01_077.c have ZERO same-name-different-layout
collisions, so each can live ONCE in a shared header that every overlay includes (via engine_core.h),
letting the struct-using shared functions propagate fleet-wide.

This tool collects every NAMED `struct X {...}` / `union X {...}` definition (brace-matched, in
document order — already compile-valid since the source compiles), and writes a guarded header with
forward declarations for all of them followed by the full definitions in source order. Anonymous
`struct {` defs are left in place (no name -> no cross-macro collision). With --strip, it also removes
those definitions from the source .c (they come from the header instead) — byte-neutral (type defs
emit no code); verify with `make check`.

Usage:
  tools/build_engine_types.py --source ov_SC01_077 --out src/shared/engine_types.h [--strip]
"""
import argparse, os, re, sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
NAMED_DEF_RE = re.compile(r'\b(struct|union)\s+([A-Za-z_]\w*)\s*\{')


def find_defs(text):
    """Return [(kind, name, start, end)] for each named struct/union DEFINITION, brace-matched.
    end is the index just past the closing '}' (the trailing ';' is consumed separately)."""
    out = []
    for m in NAMED_DEF_RE.finditer(text):
        kind, name = m.group(1), m.group(2)
        i = m.end() - 1  # at the '{'
        depth, j = 0, i
        while j < len(text):
            if text[j] == '{':
                depth += 1
            elif text[j] == '}':
                depth -= 1
                if depth == 0:
                    break
            j += 1
        # consume everything after the closing '}' up to AND INCLUDING the next ';' — this covers
        # a trailing __attribute__((packed, aligned(1))), a typedef alias, or a var name (no ';'
        # occurs inside an attribute list, which uses ','). j is at the closing '}'.
        k = j + 1
        while k < len(text) and text[k] != ';':
            k += 1
        if k < len(text):
            k += 1  # include the ';'
        out.append((kind, name, m.start(), k))
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--source', default='ov_SC01_077')
    ap.add_argument('--out', default='src/shared/engine_types.h')
    ap.add_argument('--strip', action='store_true', help='also remove the defs from the source .c')
    args = ap.parse_args()

    c_path = os.path.join(REPO, f'src/{args.source}/{args.source}.c')
    text = open(c_path).read()
    defs = find_defs(text)
    if not defs:
        sys.exit('no named struct/union defs found')

    # dedup by name (keep first; scoped check already proved 0 layout collisions)
    seen, ordered = set(), []
    for kind, name, s, e in defs:
        key = (kind, name)
        body = text[s:e]
        if key in seen:
            continue
        seen.add(key)
        ordered.append((kind, name, body))

    guard = 'BFM_ENGINE_TYPES_H'
    out = [f'#ifndef {guard}', f'#define {guard}',
           '/* src/shared/engine_types.h — shared engine struct/union types (Phase 15 §14c).',
           ' * Generated by tools/build_engine_types.py from the matched bodies in the source overlay.',
           ' * Defined ONCE here (0 same-name-different-layout collisions) so struct-using shared',
           ' * functions propagate fleet-wide via engine_core.h. Included by common.h consumers. */',
           '#include "common.h"', '']
    # forward decls first (lets pointer-only references resolve regardless of order)
    for kind, name, _ in ordered:
        out.append(f'{kind} {name};')
    out.append('')
    # full definitions in source order (source order is compile-valid for by-value nesting)
    for kind, name, body in ordered:
        out.append(body if body.rstrip().endswith(';') else body + ';')
        out.append('')
    out.append(f'#endif /* {guard} */')
    out_path = os.path.join(REPO, args.out)
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    open(out_path, 'w').write('\n'.join(out) + '\n')
    print(f'wrote {args.out}: {len(ordered)} named types (forward decls + defs, source order)')

    if args.strip:
        # remove the def spans from the source, last-first to keep offsets valid
        spans = sorted([(s, e) for _, _, s, e in defs], key=lambda t: t[0], reverse=True)
        new = text
        for s, e in spans:
            new = new[:s] + new[e:]
        # collapse the blank-line runs the removals leave
        new = re.sub(r'\n[ \t]*\n[ \t]*\n+', '\n\n', new)
        open(c_path, 'w').write(new)
        print(f'stripped {len(spans)} struct/union defs from {args.source}.c (verify byte-identical)')


if __name__ == '__main__':
    main()
