#!/usr/bin/env python3
"""EXE-wide duplicate-function report (G7 "duplicates first") — intra-binary repurpose of
match_protos.py. Finds functions in SLUS_007.26 that are byte-identical (h_exact) or
structurally identical (h_norm) to each other, so one match can be shared to the rest
(match-once-share-many). Ghidra-free; consumes .run/sig.SLUS_007.26.jsonl (regenerate
with `make sig-refresh` when the Ghidra DB changes). Writes docs/duplicates.md.

Usage: tools/dup_report.py [MIN_INS]   (default 8 — ignore trivial stubs)
"""
import json, sys, hashlib, pathlib
from collections import defaultdict

ROOT = pathlib.Path(__file__).resolve().parent.parent
SIG  = ROOT / ".run" / "sig.SLUS_007.26.jsonl"
MD   = ROOT / "docs" / "duplicates.md"

def main():
    minins = int(sys.argv[1]) if len(sys.argv) > 1 else 8
    raw = SIG.read_bytes()
    sig_sha = hashlib.sha1(raw).hexdigest()
    rows = [json.loads(l) for l in raw.decode().splitlines() if l.strip()]
    funcs = [r for r in rows if r['nins'] >= minins and r.get('src') != 'IMPORTED']

    out = ["# EXE-wide duplicate function groups  (generated by tools/dup_report.py)",
           f"# sig: .run/sig.SLUS_007.26.jsonl  sha1={sig_sha}  ({len(rows)} funcs, {len(funcs)} with nins>={minins})",
           "# Match the representative once -> share the body to the duplicates (h_exact = guaranteed",
           "# byte-match; h_norm = same source, re-point any single address constant).", ""]

    for tier, label in (('h_exact', 'byte-identical'), ('h_norm', 'structural')):
        idx = defaultdict(list)
        for r in funcs:
            idx[r[tier]].append(r)
        groups = [g for g in idx.values() if len(g) > 1]
        groups.sort(key=lambda g: (-len(g) * g[0]['nins'], g[0]['addr']))
        redundant = sum(len(g) - 1 for g in groups)
        out.append(f"## {tier} ({label}) — nins>={minins}: {len(groups)} groups, {redundant} redundant (collapsible)")
        out.append("| score | nins | count | representative | duplicates |")
        out.append("|---|---|---|---|---|")
        for g in groups:
            g.sort(key=lambda r: r['addr'])
            rep = g[0]
            dups = " ".join(r['addr'] for r in g[1:])
            out.append(f"| {len(g)*rep['nins']} | {rep['nins']} | {len(g)} | "
                       f"{rep['name']} ({rep['addr']}) | {dups} |")
        out.append("")

    MD.write_text("\n".join(out) + "\n")
    # console summary
    for line in out:
        if line.startswith('##') or line.startswith('#'):
            print(line)

if __name__ == "__main__":
    main()
