#!/usr/bin/env python3
"""EXE-wide duplicate-function report (G7 "duplicates first") — intra-binary repurpose of
match_protos.py. Finds functions in SLUS_007.26 that are byte-identical (h_exact) or
structurally identical (h_norm) to each other, so one match can be shared to the rest
(match-once-share-many). Ghidra-free; consumes .run/sig.SLUS_007.26.jsonl (regenerate
with `make sig-refresh` when the Ghidra DB changes). Writes docs/duplicates.md.

Usage: tools/dup_report.py [MIN_INS] [--binary <alias>]   (MIN_INS default 8; binary default main)
"""
import json, sys, hashlib, pathlib
from collections import defaultdict

ROOT = pathlib.Path(__file__).resolve().parent.parent

# Per-binary config (Phase 9). main = the retail EXE (current paths = no-op default);
# a second binary (Phase 10) adds its sig/md entry.
BINARIES = {
    "main": dict(sig=".run/sig.SLUS_007.26.jsonl", md="docs/duplicates.md"),
    "resident": dict(sig=".run/sig.resident.jsonl", md="docs/duplicates.resident.md"),
}

def main():
    import argparse
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("min_ins", nargs="?", type=int, default=8)
    ap.add_argument("--binary", default="main", choices=list(BINARIES))
    a = ap.parse_args()
    minins = a.min_ins
    cfg = BINARIES[a.binary]
    SIG = ROOT / cfg["sig"]
    MD = ROOT / cfg["md"]
    if not SIG.exists():
        # The signature file is a Ghidra export (`make sig-refresh`), not present until the
        # binary's program has been analyzed + dumped. Degrade gracefully (don't crash the
        # whole `make report`) so a freshly-added binary reports before its Ghidra pass.
        MD.write_text(f"# Duplicate function groups ({a.binary})\n\n"
                      f"_No signature file yet ({cfg['sig']}). Run `make sig-refresh "
                      f"BINARY={a.binary}` after the binary's Ghidra program is analyzed._\n")
        print(f"dup_report: {cfg['sig']} absent — wrote placeholder {cfg['md']} (run sig-refresh first)")
        return
    raw = SIG.read_bytes()
    sig_sha = hashlib.sha1(raw).hexdigest()
    rows = [json.loads(l) for l in raw.decode().splitlines() if l.strip()]
    funcs = [r for r in rows if r['nins'] >= minins and r.get('src') != 'IMPORTED']

    out = ["# EXE-wide duplicate function groups  (generated by tools/dup_report.py)",
           f"# sig: {cfg['sig']}  sha1={sig_sha}  ({len(rows)} funcs, {len(funcs)} with nins>={minins})",
           "# Match the representative once -> share the body to the duplicates (h_exact = guaranteed",
           "# byte-match; h_norm = same source, re-point any single address constant).", ""]

    for tier, label in (('h_exact', 'byte-identical'), ('h_norm', 'structural')):
        idx = defaultdict(list)
        for r in funcs:
            idx[r[tier]].append(r)
        groups = [g for g in idx.values() if len(g) > 1]
        groups.sort(key=lambda g: (-len(g) * g[0]['nins'], g[0]['addr']))
        redundant = sum(len(g) - 1 for g in groups)
        out.append(f"## {tier} ({label}) — nins>={minins}: {len(groups)} groups, {redundant} redundant (collapsible)")
        out.append("| score | nins | count | representative | duplicates |")
        out.append("|---|---|---|---|---|")
        for g in groups:
            g.sort(key=lambda r: r['addr'])
            rep = g[0]
            dups = " ".join(r['addr'] for r in g[1:])
            out.append(f"| {len(g)*rep['nins']} | {rep['nins']} | {len(g)} | "
                       f"{rep['name']} ({rep['addr']}) | {dups} |")
        out.append("")

    MD.write_text("\n".join(out) + "\n")
    # console summary
    for line in out:
        if line.startswith('##') or line.startswith('#'):
            print(line)

if __name__ == "__main__":
    main()
