#!/usr/bin/env python3
"""Duplicate-function report (G7 "duplicates first") — intra-binary repurpose of
match_protos.py. Finds functions that are byte-identical (h_exact) or structurally
identical (h_norm) to each other, so one match can be shared to the rest
(match-once-share-many). Ghidra-free; consumes .run/sig.<bin>.jsonl (regenerate with
`make sig-refresh` when the Ghidra DB changes; overlay images via tools/sig_image.py).

Two modes:
  * per-binary (default): one binary's self-duplicates -> docs/duplicates[.<bin>].md
  * --cross (Phase 11): bucket EVERY binary's functions together, split into
    cross-binary (members span >1 binary -> the Phase-12/13 work queue) vs intra-binary
    groups, ranked by collapsible bytes -> docs/duplicates.cross.md

Usage: tools/dup_report.py [MIN_INS] [--binary <alias>]   (per-binary; MIN_INS default 8)
       tools/dup_report.py [MIN_INS] --cross                (cross-binary; scans all BINARIES)
"""
import json, sys, hashlib, pathlib
from collections import defaultdict

ROOT = pathlib.Path(__file__).resolve().parent.parent

# Per-binary config (Phase 9). main = the retail EXE (current paths = no-op default);
# a second binary (Phase 10) adds its sig/md entry. Phase 11's --cross scans EVERY entry
# here, so a new overlay binary (Phase 13) joins the cross report automatically. The dict
# insertion order is the report's deterministic source order (committable digests).
BINARIES = {
    "main": dict(sig=".run/sig.SLUS_007.26.jsonl", md="docs/duplicates.md"),
    "resident": dict(sig=".run/sig.resident.jsonl", md="docs/duplicates.resident.md"),
    "ov_SC01_077": dict(sig=".run/sig.ov_SC01_077.jsonl", md="docs/duplicates.ov_SC01_077.md"),
    # <<< overlays: tools/new_overlay.sh inserts ov_* entries above this line (Phase 13) >>>
}
CROSS_MD = "docs/duplicates.cross.md"


def _load_sig(rel):
    """Read a .run/sig.<bin>.jsonl -> (rows, sha1) or (None, None) if absent."""
    p = ROOT / rel
    if not p.exists():
        return None, None
    raw = p.read_bytes()
    return [json.loads(l) for l in raw.decode().splitlines() if l.strip()], hashlib.sha1(raw).hexdigest()


OV_GLOB = ".run/sig.ov_*.jsonl"   # sig_image overlay outputs (convention: ov_<SCxx>_<nnn>)
CROSS_CAP = 200                    # max groups listed per subsection (ranked by collapsible bytes)
MEMBERS_SHOWN = 4                  # sample members per group row (large groups span dozens of overlays)


def cross_report(minins):
    """Phase 11: bucket EVERY binary's functions together; emit docs/duplicates.cross.md. Sources =
    the named BINARIES (main, resident) + every sig_image overlay sig (.run/sig.ov_*.jsonl). A group
    whose members span >1 binary is a cross-binary duplicate (the dedup target an engine/overlay match
    auto-credits — the Phase-12/13 work queue); same-binary groups are where the share machinery is
    first proven. Ranked by collapsible bytes = (count-1)*nins*4 (bytes SAVED — one member stays the
    source). h_exact = guaranteed byte-match; h_norm = candidate (byte-confirm via dedup_integrate)."""
    import glob
    sources, funcs = [], []
    for alias, cfg in BINARIES.items():
        rows, sha = _load_sig(cfg["sig"])
        if rows is None:
            sources.append(f"#   {alias:10} {cfg['sig']}  (ABSENT — run sig-refresh/sig_image)")
            continue
        sources.append(f"#   {alias:10} {cfg['sig']}  sha1={sha}  ({len(rows)} funcs)")
        for r in rows:
            if r['nins'] >= minins and r.get('src') != 'IMPORTED':
                r = dict(r); r['binary'] = alias
                funcs.append(r)
    # overlay sigs (sig_image) — summarized as one source line (a set-sha makes the digest reproducible)
    ov_set = hashlib.sha1(); ov_n = 0
    for p in sorted(glob.glob(str(ROOT / OV_GLOB))):
        alias = pathlib.Path(p).name[len("sig."):-len(".jsonl")]
        rows, sha = _load_sig(str(pathlib.Path(p).relative_to(ROOT)))
        if rows is None:
            continue
        ov_set.update(sha.encode()); ov_n += 1
        for r in rows:
            if r['nins'] >= minins and r.get('src') != 'IMPORTED':
                r = dict(r); r['binary'] = alias
                funcs.append(r)
    if ov_n:
        sources.append(f"#   overlays   {ov_n}x sig.ov_*.jsonl (sig_image, nins>={minins})  set-sha1={ov_set.hexdigest()}")

    out = ["# Cross-binary duplicate function groups  (generated by tools/dup_report.py --cross)",
           "# sources:", *sources,
           "# Collapsible bytes = (count-1)*nins*4 (bytes saved; one member stays the source).",
           "# A cross-binary group (binaries>1) is the Phase-12/13 work queue; lead with h_exact",
           "# (guaranteed byte-match), h_norm is candidate-only (byte-confirm via dedup_integrate).",
           f"# Overlay sigs are sig_image (Ghidra-free): h_exact is exact; h_norm is self-consistent.",
           f"# Each subsection lists the top {CROSS_CAP} groups by collapsible bytes; totals are stated.", ""]

    def emit(groups, tier_letter, cls_letter, title):
        total_bytes = sum((len(g) - 1) * g[0]['nins'] * 4 for g in groups)
        cap = f"  (top {CROSS_CAP} of {len(groups)} shown)" if len(groups) > CROSS_CAP else ""
        out.append(f"### {title} — {len(groups)} groups, {total_bytes} collapsible bytes{cap}")
        out.append("| gid | bytes | nins | count | #bin | sample members (binary:addr) |")
        out.append("|---|---|---|---|---|---|")
        for i, g in enumerate(groups[:CROSS_CAP]):
            g = sorted(g, key=lambda r: (r['binary'], r['addr']))
            rep = g[0]
            nbin = len({r['binary'] for r in g})
            shown = "; ".join(f"{r['binary']}:{r['addr']}" for r in g[:MEMBERS_SHOWN])
            if len(g) > MEMBERS_SHOWN:
                shown += f"; …+{len(g) - MEMBERS_SHOWN}"
            out.append(f"| {tier_letter}{cls_letter}{i} | {(len(g) - 1) * rep['nins'] * 4} | {rep['nins']} | "
                       f"{len(g)} | {nbin} | {shown} |")
        out.append("")

    for tier, label, tl in (('h_exact', 'byte-identical', 'e'), ('h_norm', 'structural', 'n')):
        idx = defaultdict(list)
        for r in funcs:
            idx[r[tier]].append(r)
        groups = [g for g in idx.values() if len(g) > 1]
        cross = [g for g in groups if len({r['binary'] for r in g}) > 1]
        intra = [g for g in groups if len({r['binary'] for r in g}) == 1]
        keyf = lambda g: (-(len(g) - 1) * g[0]['nins'] * 4, min((r['binary'], r['addr']) for r in g))
        cross.sort(key=keyf); intra.sort(key=keyf)
        out.append(f"## {tier} ({label})")
        out.append("")
        emit(cross, tl, "x", "cross-binary  (binaries > 1)")
        emit(intra, tl, "i", "intra-binary")

    (ROOT / CROSS_MD).write_text("\n".join(out) + "\n")
    for line in out:
        if line.startswith('#') or line.startswith('##'):
            print(line)


def main():
    import argparse
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("min_ins", nargs="?", type=int, default=8)
    ap.add_argument("--binary", default="main", choices=list(BINARIES))
    ap.add_argument("--cross", action="store_true",
                    help="cross-binary mode: scan all BINARIES -> docs/duplicates.cross.md (ignores --binary)")
    a = ap.parse_args()
    minins = a.min_ins
    if a.cross:
        cross_report(minins)
        return
    cfg = BINARIES[a.binary]
    SIG = ROOT / cfg["sig"]
    MD = ROOT / cfg["md"]
    if not SIG.exists():
        # The signature file is a Ghidra export (`make sig-refresh`), not present until the
        # binary's program has been analyzed + dumped. Degrade gracefully (don't crash the
        # whole `make report`) so a freshly-added binary reports before its Ghidra pass.
        MD.write_text(f"# Duplicate function groups ({a.binary})\n\n"
                      f"_No signature file yet ({cfg['sig']}). Run `make sig-refresh "
                      f"BINARY={a.binary}` after the binary's Ghidra program is analyzed._\n")
        print(f"dup_report: {cfg['sig']} absent — wrote placeholder {cfg['md']} (run sig-refresh first)")
        return
    raw = SIG.read_bytes()
    sig_sha = hashlib.sha1(raw).hexdigest()
    rows = [json.loads(l) for l in raw.decode().splitlines() if l.strip()]
    funcs = [r for r in rows if r['nins'] >= minins and r.get('src') != 'IMPORTED']

    out = ["# EXE-wide duplicate function groups  (generated by tools/dup_report.py)",
           f"# sig: {cfg['sig']}  sha1={sig_sha}  ({len(rows)} funcs, {len(funcs)} with nins>={minins})",
           "# Match the representative once -> share the body to the duplicates (h_exact = guaranteed",
           "# byte-match; h_norm = same source, re-point any single address constant).", ""]

    for tier, label in (('h_exact', 'byte-identical'), ('h_norm', 'structural')):
        idx = defaultdict(list)
        for r in funcs:
            idx[r[tier]].append(r)
        groups = [g for g in idx.values() if len(g) > 1]
        groups.sort(key=lambda g: (-len(g) * g[0]['nins'], g[0]['addr']))
        redundant = sum(len(g) - 1 for g in groups)
        out.append(f"## {tier} ({label}) — nins>={minins}: {len(groups)} groups, {redundant} redundant (collapsible)")
        out.append("| score | nins | count | representative | duplicates |")
        out.append("|---|---|---|---|---|")
        for g in groups:
            g.sort(key=lambda r: r['addr'])
            rep = g[0]
            dups = " ".join(r['addr'] for r in g[1:])
            out.append(f"| {len(g)*rep['nins']} | {rep['nins']} | {len(g)} | "
                       f"{rep['name']} ({rep['addr']}) | {dups} |")
        out.append("")

    MD.write_text("\n".join(out) + "\n")
    # console summary
    for line in out:
        if line.startswith('##') or line.startswith('#'):
            print(line)

if __name__ == "__main__":
    main()
