#!/usr/bin/env python3
"""Phase-25 T2: the ranked STRUCTURAL-FAMILY target manifest for the idiom-curriculum endgame.

Regroups the UNMATCHED frontier by structure (h_norm) instead of bytes (h_exact) — the Phase-24 reframe —
and emits, per family, the ONE exemplar to draft (its ov_SC01_077 member where present: the canonical harvest
overlay with cached Ghidra-C) + the family's leverage. An h_norm family is RELOC-ONLY by construction
(sig_image.norm_stream masks only jal/HI16/LO16, keeping registers+true immediates), so its members differ
ONLY in per-overlay symbol addresses; whether ONE C body matches all members is confirmed per-family by the
whole-binary byte-gate (T3 proves the magnitude; T7 banks each). Leverage = the family's INSTANCE count (how
many overlays carry it), NOT h_exact-reach (which is ~1-3 for a byte-shattered family).

  .venv/bin/python tools/family_manifest.py
  -> .run/family_manifest.json (full, ranked by byte-weight) + docs/family-manifest.md (digest, committed)

Ground truth = the sigs (they sign the ORIGINAL bytes, stable across matching); reproducible via
`make sig-overlays`. Companion to the frontier surveys .run/{analyze_frontier,probe_hnorm}.py.
"""
import json, glob, re, collections

sig_by_ov = {}
for p in sorted(glob.glob(".run/sig.ov_*.jsonl")):
    ov = p.split("sig.")[1][:-6]
    recs = {}
    for line in open(p):
        line = line.strip()
        if not line:
            continue
        d = json.loads(line)
        recs[int(d["addr"], 16)] = (d["nins"], d["h_exact"], d["h_norm"])
    sig_by_ov[ov] = recs

# matched set (h_exact): ov_SC01_077's non-stub functions + every dedup-registered hash
src077 = "".join(open(cf).read() for cf in glob.glob("src/ov_SC01_077/*.c"))
stub077 = set(int(m, 16) for m in re.findall(r'INCLUDE_ASM\([^)]*,\s*func_([0-9A-Fa-f]+)\)', src077))
sig077 = sig_by_ov.get("ov_SC01_077", {})
matched_hex = {hx for v, (n, hx, hn) in sig077.items() if v not in stub077}
matched_hex |= set(re.findall(r'hash:\s*([0-9a-f]{40})', open("config/dedup.us.yaml").read()))

# per h_exact class: {ovs, nins, rep_vram (ov_SC01_077's if present), h_norm}
hexcls = {}
for ov, recs in sig_by_ov.items():
    for v, (n, hx, hn) in recs.items():
        e = hexcls.setdefault(hx, [set(), n, v, hn])
        e[0].add(ov)
        if ov == "ov_SC01_077":
            e[2] = v

# UNMATCHED h_exact classes -> group by h_norm (the structural family)
fam = collections.defaultdict(lambda: {"hexclasses": 0, "instances": 0, "nins": 0, "bw": 0, "rep": 0, "maxhexreach": 0})
for hx, (ovs, n, v, hn) in hexcls.items():
    if hx in matched_hex:
        continue
    r = len(ovs)
    f = fam[hn]
    f["hexclasses"] += 1
    f["instances"] += r                 # fleet-wide member count = the x-N propagation leverage
    f["bw"] += r * n * 4
    f["maxhexreach"] = max(f["maxhexreach"], r)
    if n >= f["nins"] or f["rep"] == 0:
        f["rep"] = v
        f["nins"] = n

# the draftable exemplar per family: the largest UNMATCHED ov_SC01_077 stub whose h_norm == the family
ov077_ex = {}   # h_norm -> (vram, nins)
for v, (n, hx, hn) in sig077.items():
    if v not in stub077 or hx in matched_hex:
        continue
    if hn not in ov077_ex or n > ov077_ex[hn][1]:
        ov077_ex[hn] = (v, n)


def bucket(n):
    return "tiny" if n < 20 else "small" if n < 50 else "med" if n < 100 else "large" if n < 150 else "GIANT"


rows = []
for hn, f in fam.items():
    ex = ov077_ex.get(hn)
    rows.append({
        "hnorm": hn,
        "rep_addr": f"0x{f['rep']:08x}",
        "ov077_exemplar": (f"0x{ex[0]:08x}" if ex else None),
        "n_hexcls": f["hexclasses"],
        "instances": f["instances"],
        "max_nins": f["nins"],
        "max_hex_reach": f["maxhexreach"],
        "byte_weight": f["bw"],
        "size_bucket": bucket(f["nins"]),
        "multi_member": f["hexclasses"] >= 2,
    })
rows.sort(key=lambda r: -r["byte_weight"])
json.dump(rows, open(".run/family_manifest.json", "w"), indent=0)

multi = [r for r in rows if r["multi_member"]]
with_ex = [r for r in multi if r["ov077_exemplar"]]

# classify the multi-member families by ov_SC01_077 membership -> the endgame's 3 levers
ov077_matched_hn = {hn for v, (n, hx, hn) in sig077.items() if v not in stub077 or hx in matched_hex}
lev = {"draftable": [0, 0], "matched_free": [0, 0], "absent": [0, 0]}
for r in multi:
    k = "draftable" if r["ov077_exemplar"] else ("matched_free" if r["hnorm"] in ov077_matched_hn else "absent")
    lev[k][0] += 1
    lev[k][1] += r["byte_weight"]

L = ["# Phase 25 — Structural-family target manifest (T2)\n"]
L.append("> Generated by `tools/family_manifest.py` from the 134 overlay sigs + ov_SC01_077 matched set + "
         "`config/dedup.us.yaml`. One exemplar per h_norm family, drafted from its **ov_SC01_077 member** where "
         "present. h_norm families are reloc-only by construction; whether one C body matches all members is "
         "confirmed per-family by the byte-gate (T3 magnitude / T7 banks). **Leverage = `inst` (fleet-wide member "
         "count), NOT `hexR` (h_exact-reach, ~1-3 for byte-shattered families).**\n")
L.append(f"**Families:** {len(rows)} · **multi-member (hidden leverage):** {len(multi)} / "
         f"{sum(r['byte_weight'] for r in multi)/1e6:.1f} MB · **with an ov_SC01_077 draftable exemplar:** {len(with_ex)}.\n")
L.append(f"**Endgame levers** (multi-member families × ov_SC01_077 membership): **draftable** {lev['draftable'][0]} / "
         f"{lev['draftable'][1]/1e6:.1f} MB (unmatched ov077 member → draft the exemplar, T5/T7) · **matched-free** "
         f"{lev['matched_free'][0]} / {lev['matched_free'][1]/1e6:.1f} MB (matched ov077 member + unmatched siblings → "
         f"free `--tier h_norm` propagation, T3) · **absent** {lev['absent'][0]} / {lev['absent'][1]/1e6:.1f} MB "
         f"(no ov077 member → draft from another overlay).\n")
L.append("| # | rep addr | ov077 exemplar | nins | hexcls | inst | hexR | byteMB | bucket |")
L.append("|--:|----------|----------------|-----:|-------:|-----:|-----:|-------:|--------|")
for i, r in enumerate(multi[:60], 1):
    L.append(f"| {i} | {r['rep_addr']} | {r['ov077_exemplar'] or '—'} | {r['max_nins']} | {r['n_hexcls']} | "
             f"{r['instances']} | {r['max_hex_reach']} | {r['byte_weight']/1e6:.2f} | {r['size_bucket']} |")
open("docs/family-manifest.md", "w").write("\n".join(L) + "\n")

print(f"families {len(rows)} | multi-member {len(multi)} ({sum(r['byte_weight'] for r in multi)/1e6:.1f} MB) | "
      f"ov077-draftable {len(with_ex)}")
print(f"levers: draftable {lev['draftable'][0]}/{lev['draftable'][1]/1e6:.1f}MB | "
      f"matched-free {lev['matched_free'][0]}/{lev['matched_free'][1]/1e6:.1f}MB | "
      f"absent {lev['absent'][0]}/{lev['absent'][1]/1e6:.1f}MB")
print("-> .run/family_manifest.json + docs/family-manifest.md")

# T3-ready picks: mid-size (100-150 ins) multi-member family, ov077-draftable, spanning most overlays
t3 = [r for r in multi if r["ov077_exemplar"] and 100 <= r["max_nins"] <= 150 and r["instances"] >= 100]
t3.sort(key=lambda r: (-r["instances"], -r["byte_weight"]))
print("\nT3 swing-question candidates (mid-size 100-150 ins, ov077-draftable, inst>=100):")
for r in t3[:10]:
    print(f"  ex={r['ov077_exemplar']} nins={r['max_nins']} inst={r['instances']} hexcls={r['n_hexcls']} "
          f"bw={r['byte_weight']/1e6:.2f}MB")
